#############################################################################
# Makefile for building: test_a
# Generated by qmake (2.01a) (Qt 4.8.6) on: Sun Apr 24 01:45:18 2016
# Project:  test_a.pro
# Template: app
# Command: /usr/lib/arm-linux-gnueabihf/qt4/bin/qmake -o Makefile test_a.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/local/include/xlslib/  -I./include  -I/usr/include/qt4 -I/home/pi/qt/qwt/src -I/usr/local/libxls/include -I. -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/arm-linux-gnueabihf -L./lib -L/usr/local/lib -L/usr/local/libxls/lib  -lreader -lxlsreader  -lxls -lqwt -lQtGui -lQtCore -lpthread -lwiringPi
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/arm-linux-gnueabihf/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = aboutwidget.cpp \
		analyzeresult.cpp \
		chargeform.cpp \
		commondial.cpp \
		custommessagebox.cpp \
		dataworkerthread.cpp \
		digitalinputpanel.cpp \
		digitalinputpanelcontext.cpp \
		energyparam.cpp \
		filecopyer.cpp \
		filewidget.cpp \
		fullinputpanel.cpp \
		main.cpp \
		mainwindow.cpp \
		readerworkthread.cpp \
		recordworkthread.cpp \
		sysparam.cpp \
		util.cpp \
		XlsReader.cpp moc_aboutwidget.cpp \
		moc_chargeform.cpp \
		moc_custommessagebox.cpp \
		moc_dataworkerthread.cpp \
		moc_digitalinputpanel.cpp \
		moc_digitalinputpanelcontext.cpp \
		moc_filecopyer.cpp \
		moc_filewidget.cpp \
		moc_fullinputpanel.cpp \
		moc_mainwindow.cpp \
		moc_readerworkthread.cpp \
		moc_recordworkthread.cpp
OBJECTS       = aboutwidget.o \
		analyzeresult.o \
		chargeform.o \
		commondial.o \
		custommessagebox.o \
		dataworkerthread.o \
		digitalinputpanel.o \
		digitalinputpanelcontext.o \
		energyparam.o \
		filecopyer.o \
		filewidget.o \
		fullinputpanel.o \
		main.o \
		mainwindow.o \
		readerworkthread.o \
		recordworkthread.o \
		sysparam.o \
		util.o \
		XlsReader.o \
		moc_aboutwidget.o \
		moc_chargeform.o \
		moc_custommessagebox.o \
		moc_dataworkerthread.o \
		moc_digitalinputpanel.o \
		moc_digitalinputpanelcontext.o \
		moc_filecopyer.o \
		moc_filewidget.o \
		moc_fullinputpanel.o \
		moc_mainwindow.o \
		moc_readerworkthread.o \
		moc_recordworkthread.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		test_a.pro
QMAKE_TARGET  = test_a
DESTDIR       = 
TARGET        = test_a

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_aboutwidget.h ui_chargeform.h ui_custommessagebox.h ui_digitalinputpanel.h ui_filewidget.h ui_fullinputpanel.h ui_mainwindow\ 固力.h ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: test_a.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/arm-linux-gnueabihf/libQtGui.prl \
		/usr/lib/arm-linux-gnueabihf/libQtCore.prl
	$(QMAKE) -o Makefile test_a.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/arm-linux-gnueabihf/libQtGui.prl:
/usr/lib/arm-linux-gnueabihf/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile test_a.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/test_a1.0.0 || $(MKDIR) .tmp/test_a1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/test_a1.0.0/ && $(COPY_FILE) --parents aboutwidget.h analyzeresult.h chargeform.h commondial.h const_define.h custommessagebox.h dataworkerthread.h digitalinputpanel.h digitalinputpanelcontext.h energyparam.h filecopyer.h filewidget.h fullinputpanel.h mainwindow.h readerworkthread.h recordworkthread.h sysparam.h util.h wiringPi.h wiringSerial.h XlsReader.h include/wiringPi.h include/wiringSerial.h .tmp/test_a1.0.0/ && $(COPY_FILE) --parents aboutwidget.cpp analyzeresult.cpp chargeform.cpp commondial.cpp custommessagebox.cpp dataworkerthread.cpp digitalinputpanel.cpp digitalinputpanelcontext.cpp energyparam.cpp filecopyer.cpp filewidget.cpp fullinputpanel.cpp main.cpp mainwindow.cpp readerworkthread.cpp recordworkthread.cpp sysparam.cpp util.cpp XlsReader.cpp .tmp/test_a1.0.0/ && $(COPY_FILE) --parents aboutwidget.ui chargeform.ui custommessagebox.ui digitalinputpanel.ui filewidget.ui fullinputpanel.ui mainwindow 固力.ui mainwindow.ui .tmp/test_a1.0.0/ && (cd `dirname .tmp/test_a1.0.0` && $(TAR) test_a1.0.0.tar test_a1.0.0 && $(COMPRESS) test_a1.0.0.tar) && $(MOVE) `dirname .tmp/test_a1.0.0`/test_a1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/test_a1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_aboutwidget.cpp moc_chargeform.cpp moc_custommessagebox.cpp moc_dataworkerthread.cpp moc_digitalinputpanel.cpp moc_digitalinputpanelcontext.cpp moc_filecopyer.cpp moc_filewidget.cpp moc_fullinputpanel.cpp moc_mainwindow.cpp moc_readerworkthread.cpp moc_recordworkthread.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_aboutwidget.cpp moc_chargeform.cpp moc_custommessagebox.cpp moc_dataworkerthread.cpp moc_digitalinputpanel.cpp moc_digitalinputpanelcontext.cpp moc_filecopyer.cpp moc_filewidget.cpp moc_fullinputpanel.cpp moc_mainwindow.cpp moc_readerworkthread.cpp moc_recordworkthread.cpp
moc_aboutwidget.cpp: aboutwidget.h
	/usr/lib/arm-linux-gnueabihf/qt4/bin/moc $(DEFINES) $(INCPATH) aboutwidget.h -o moc_aboutwidget.cpp

moc_chargeform.cpp: const_define.h \
		chargeform.h
	/usr/lib/arm-linux-gnueabihf/qt4/bin/moc $(DEFINES) $(INCPATH) chargeform.h -o moc_chargeform.cpp

moc_custommessagebox.cpp: custommessagebox.h
	/usr/lib/arm-linux-gnueabihf/qt4/bin/moc $(DEFINES) $(INCPATH) custommessagebox.h -o moc_custommessagebox.cpp

moc_dataworkerthread.cpp: wiringPi.h \
		wiringSerial.h \
		energyparam.h \
		dataworkerthread.h
	/usr/lib/arm-linux-gnueabihf/qt4/bin/moc $(DEFINES) $(INCPATH) dataworkerthread.h -o moc_dataworkerthread.cpp

moc_digitalinputpanel.cpp: ui_digitalinputpanel.h \
		digitalinputpanel.h
	/usr/lib/arm-linux-gnueabihf/qt4/bin/moc $(DEFINES) $(INCPATH) digitalinputpanel.h -o moc_digitalinputpanel.cpp

moc_digitalinputpanelcontext.cpp: digitalinputpanel.h \
		ui_digitalinputpanel.h \
		digitalinputpanelcontext.h
	/usr/lib/arm-linux-gnueabihf/qt4/bin/moc $(DEFINES) $(INCPATH) digitalinputpanelcontext.h -o moc_digitalinputpanelcontext.cpp

moc_filecopyer.cpp: util.h \
		analyzeresult.h \
		filecopyer.h
	/usr/lib/arm-linux-gnueabihf/qt4/bin/moc $(DEFINES) $(INCPATH) filecopyer.h -o moc_filecopyer.cpp

moc_filewidget.cpp: filewidget.h
	/usr/lib/arm-linux-gnueabihf/qt4/bin/moc $(DEFINES) $(INCPATH) filewidget.h -o moc_filewidget.cpp

moc_fullinputpanel.cpp: fullinputpanel.h
	/usr/lib/arm-linux-gnueabihf/qt4/bin/moc $(DEFINES) $(INCPATH) fullinputpanel.h -o moc_fullinputpanel.cpp

moc_mainwindow.cpp: sysparam.h \
		const_define.h \
		recordworkthread.h \
		dataworkerthread.h \
		wiringPi.h \
		wiringSerial.h \
		energyparam.h \
		analyzeresult.h \
		commondial.h \
		custommessagebox.h \
		filewidget.h \
		readerworkthread.h \
		XlsReader.h \
		chargeform.h \
		filecopyer.h \
		util.h \
		aboutwidget.h \
		mainwindow.h
	/usr/lib/arm-linux-gnueabihf/qt4/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_readerworkthread.cpp: XlsReader.h \
		analyzeresult.h \
		readerworkthread.h
	/usr/lib/arm-linux-gnueabihf/qt4/bin/moc $(DEFINES) $(INCPATH) readerworkthread.h -o moc_readerworkthread.cpp

moc_recordworkthread.cpp: dataworkerthread.h \
		wiringPi.h \
		wiringSerial.h \
		energyparam.h \
		analyzeresult.h \
		const_define.h \
		recordworkthread.h
	/usr/lib/arm-linux-gnueabihf/qt4/bin/moc $(DEFINES) $(INCPATH) recordworkthread.h -o moc_recordworkthread.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_aboutwidget.h ui_chargeform.h ui_custommessagebox.h ui_digitalinputpanel.h ui_filewidget.h ui_fullinputpanel.h ui_mainwindow\ 固力.h ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_aboutwidget.h ui_chargeform.h ui_custommessagebox.h ui_digitalinputpanel.h ui_filewidget.h ui_fullinputpanel.h ui_mainwindow 固力.h ui_mainwindow.h
ui_aboutwidget.h: aboutwidget.ui
	/usr/lib/arm-linux-gnueabihf/qt4/bin/uic aboutwidget.ui -o ui_aboutwidget.h

ui_chargeform.h: chargeform.ui
	/usr/lib/arm-linux-gnueabihf/qt4/bin/uic chargeform.ui -o ui_chargeform.h

ui_custommessagebox.h: custommessagebox.ui
	/usr/lib/arm-linux-gnueabihf/qt4/bin/uic custommessagebox.ui -o ui_custommessagebox.h

ui_digitalinputpanel.h: digitalinputpanel.ui
	/usr/lib/arm-linux-gnueabihf/qt4/bin/uic digitalinputpanel.ui -o ui_digitalinputpanel.h

ui_filewidget.h: filewidget.ui
	/usr/lib/arm-linux-gnueabihf/qt4/bin/uic filewidget.ui -o ui_filewidget.h

ui_fullinputpanel.h: fullinputpanel.ui
	/usr/lib/arm-linux-gnueabihf/qt4/bin/uic fullinputpanel.ui -o ui_fullinputpanel.h

ui_mainwindow\ 固力.h: mainwindow\ 固力.ui
	/usr/lib/arm-linux-gnueabihf/qt4/bin/uic mainwindow\ 固力.ui -o ui_mainwindow\ 固力.h

ui_mainwindow.h: mainwindow.ui
	/usr/lib/arm-linux-gnueabihf/qt4/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

aboutwidget.o: aboutwidget.cpp aboutwidget.h \
		ui_aboutwidget.h \
		const_define.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o aboutwidget.o aboutwidget.cpp

analyzeresult.o: analyzeresult.cpp analyzeresult.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o analyzeresult.o analyzeresult.cpp

chargeform.o: chargeform.cpp chargeform.h \
		const_define.h \
		ui_chargeform.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o chargeform.o chargeform.cpp

commondial.o: commondial.cpp commondial.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o commondial.o commondial.cpp

custommessagebox.o: custommessagebox.cpp custommessagebox.h \
		ui_custommessagebox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o custommessagebox.o custommessagebox.cpp

dataworkerthread.o: dataworkerthread.cpp dataworkerthread.h \
		wiringPi.h \
		wiringSerial.h \
		energyparam.h \
		util.h \
		analyzeresult.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dataworkerthread.o dataworkerthread.cpp

digitalinputpanel.o: digitalinputpanel.cpp digitalinputpanel.h \
		ui_digitalinputpanel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o digitalinputpanel.o digitalinputpanel.cpp

digitalinputpanelcontext.o: digitalinputpanelcontext.cpp digitalinputpanelcontext.h \
		digitalinputpanel.h \
		ui_digitalinputpanel.h \
		util.h \
		analyzeresult.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o digitalinputpanelcontext.o digitalinputpanelcontext.cpp

energyparam.o: energyparam.cpp energyparam.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o energyparam.o energyparam.cpp

filecopyer.o: filecopyer.cpp filecopyer.h \
		util.h \
		analyzeresult.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o filecopyer.o filecopyer.cpp

filewidget.o: filewidget.cpp filewidget.h \
		ui_filewidget.h \
		util.h \
		analyzeresult.h \
		const_define.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o filewidget.o filewidget.cpp

fullinputpanel.o: fullinputpanel.cpp fullinputpanel.h \
		ui_fullinputpanel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fullinputpanel.o fullinputpanel.cpp

main.o: main.cpp mainwindow.h \
		sysparam.h \
		const_define.h \
		recordworkthread.h \
		dataworkerthread.h \
		wiringPi.h \
		wiringSerial.h \
		energyparam.h \
		analyzeresult.h \
		commondial.h \
		custommessagebox.h \
		filewidget.h \
		readerworkthread.h \
		XlsReader.h \
		chargeform.h \
		filecopyer.h \
		util.h \
		aboutwidget.h \
		digitalinputpanelcontext.h \
		digitalinputpanel.h \
		ui_digitalinputpanel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		sysparam.h \
		const_define.h \
		recordworkthread.h \
		dataworkerthread.h \
		wiringPi.h \
		wiringSerial.h \
		energyparam.h \
		analyzeresult.h \
		commondial.h \
		custommessagebox.h \
		filewidget.h \
		readerworkthread.h \
		XlsReader.h \
		chargeform.h \
		filecopyer.h \
		util.h \
		aboutwidget.h \
		ui_mainwindow.h \
		digitalinputpanelcontext.h \
		digitalinputpanel.h \
		ui_digitalinputpanel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

readerworkthread.o: readerworkthread.cpp readerworkthread.h \
		XlsReader.h \
		analyzeresult.h \
		util.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o readerworkthread.o readerworkthread.cpp

recordworkthread.o: recordworkthread.cpp recordworkthread.h \
		dataworkerthread.h \
		wiringPi.h \
		wiringSerial.h \
		energyparam.h \
		analyzeresult.h \
		const_define.h \
		util.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o recordworkthread.o recordworkthread.cpp

sysparam.o: sysparam.cpp sysparam.h \
		const_define.h \
		util.h \
		analyzeresult.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sysparam.o sysparam.cpp

util.o: util.cpp const_define.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o util.o util.cpp

XlsReader.o: XlsReader.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o XlsReader.o XlsReader.cpp

moc_aboutwidget.o: moc_aboutwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_aboutwidget.o moc_aboutwidget.cpp

moc_chargeform.o: moc_chargeform.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_chargeform.o moc_chargeform.cpp

moc_custommessagebox.o: moc_custommessagebox.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_custommessagebox.o moc_custommessagebox.cpp

moc_dataworkerthread.o: moc_dataworkerthread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dataworkerthread.o moc_dataworkerthread.cpp

moc_digitalinputpanel.o: moc_digitalinputpanel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_digitalinputpanel.o moc_digitalinputpanel.cpp

moc_digitalinputpanelcontext.o: moc_digitalinputpanelcontext.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_digitalinputpanelcontext.o moc_digitalinputpanelcontext.cpp

moc_filecopyer.o: moc_filecopyer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_filecopyer.o moc_filecopyer.cpp

moc_filewidget.o: moc_filewidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_filewidget.o moc_filewidget.cpp

moc_fullinputpanel.o: moc_fullinputpanel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_fullinputpanel.o moc_fullinputpanel.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_readerworkthread.o: moc_readerworkthread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_readerworkthread.o moc_readerworkthread.cpp

moc_recordworkthread.o: moc_recordworkthread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_recordworkthread.o moc_recordworkthread.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

