######################################################################
# Automatically generated by qmake (2.01a) Wed Jun 15 08:10:20 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . include
INCLUDEPATH += .

# Input
HEADERS += aboutwidget.h \
           analyzeresult.h \
           chargeform.h \
           commondial.h \
           const_define.h \
           custommessagebox.h \
           dataworkerthread.h \
           digitalinputpanel.h \
           digitalinputpanelcontext.h \
           energyparam.h \
           filecopyer.h \
           filewidget.h \
           fullinputpanel.h \
           mainwindow.h \
           readerworkthread.h \
           recordworkthread.h \
           sysparam.h \
           util.h \
           wiringPi.h \
           wiringSerial.h \
           XlsReader.h \
           include/wiringPi.h \
           include/wiringSerial.h
FORMS += aboutwidget.ui \
         chargeform.ui \
         custommessagebox.ui \
         digitalinputpanel.ui \
         filewidget.ui \
         fullinputpanel.ui \
         mainwindow.ui
SOURCES += aboutwidget.cpp \
           analyzeresult.cpp \
           chargeform.cpp \
           commondial.cpp \
           custommessagebox.cpp \
           dataworkerthread.cpp \
           digitalinputpanel.cpp \
           digitalinputpanelcontext.cpp \
           energyparam.cpp \
           filecopyer.cpp \
           filewidget.cpp \
           fullinputpanel.cpp \
           main.cpp \
           mainwindow.cpp \
           readerworkthread.cpp \
           recordworkthread.cpp \
           sysparam.cpp \
           util.cpp \
           XlsReader.cpp
