######################################################################
# Automatically generated by qmake (2.01a) Thu Mar 17 11:22:55 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += digitalinputpanel.h \
           digitalinputpanelcontext.h \
           mainwindow.h \
           sysparam.h \
    util.h \
    dataworkerthread.h \
    recordworkthread.h \
    energyparam.h \
    commondial.h \
    custommessagebox.h \
    filewidget.h
FORMS += digitalinputpanel.ui mainwindow.ui \
    custommessagebox.ui \
    filewidget.ui
SOURCES += digitalinputpanel.cpp \
           digitalinputpanelcontext.cpp \
           main.cpp \
           mainwindow.cpp \
           sysparam.cpp \
    util.cpp \
    dataworkerthread.cpp \
    recordworkthread.cpp \
    energyparam.cpp \
    commondial.cpp \
    custommessagebox.cpp \
    filewidget.cpp
