######################################################################
# Automatically generated by qmake (2.01a) Tue Apr 19 00:33:24 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . include
INCLUDEPATH += . include

# Input
HEADERS += analyzeresult.h \
           chargeform.h \
           commondial.h \
           const_define.h \
           custommessagebox.h \
           dataworkerthread.h \
           digitalinputpanel.h \
           digitalinputpanelcontext.h \
           energyparam.h \
           filewidget.h \
           mainwindow.h \
           readerworkthread.h \
           recordworkthread.h \
           sysparam.h \
           util.h \
           XlsReader.h \
           include/wiringPi.h \
           include/wiringSerial.h
FORMS += chargeform.ui \
         custommessagebox.ui \
         digitalinputpanel.ui \
         filewidget.ui \
         "mainwindow 固力.ui" \
         mainwindow.ui
SOURCES += analyzeresult.cpp \
           chargeform.cpp \
           commondial.cpp \
           custommessagebox.cpp \
           dataworkerthread.cpp \
           digitalinputpanel.cpp \
           digitalinputpanelcontext.cpp \
           energyparam.cpp \
           filewidget.cpp \
           main.cpp \
           mainwindow.cpp \
           readerworkthread.cpp \
           recordworkthread.cpp \
           sysparam.cpp \
           util.cpp \
           XlsReader.cpp
