/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 4.8.6
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QComboBox>
#include <QtGui/QFrame>
#include <QtGui/QHeaderView>
#include <QtGui/QLCDNumber>
#include <QtGui/QLabel>
#include <QtGui/QLineEdit>
#include <QtGui/QMainWindow>
#include <QtGui/QPushButton>
#include <QtGui/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralWidget;
    QFrame *line;
    QLabel *label;
    QLabel *label_2;
    QWidget *widget;
    QLabel *label_IPower_name_180;
    QLabel *label_IPower_name_179;
    QLabel *label_IPower_name_181;
    QLabel *label_IPower_name_182;
    QLabel *label_IPower_name_183;
    QLabel *label_IPower_name_189;
    QLabel *label_IPower_name_190;
    QLabel *label_IPower_name_191;
    QLabel *label_IPower_name_200;
    QPushButton *pushButton_12;
    QLineEdit *lineEdit_radio;
    QLineEdit *lineEdit_charge;
    QLineEdit *lineEdit_power;
    QLineEdit *lineEdit_current_idle_max;
    QLineEdit *lineEdit_loading_pressure;
    QLineEdit *lineEdit_gas;
    QLineEdit *lineEdit_current_down_max;
    QLineEdit *lineEdit_unloading_pressure;
    QComboBox *comboBox_store_type;
    QLabel *label_IPower_name_184;
    QLabel *label_IPower_name_185;
    QLabel *label_IPower_name_186;
    QLabel *label_IPower_name_187;
    QLabel *label_IPower_name_188;
    QLabel *label_IPower_name_192;
    QLabel *label_gas_produce_rated;
    QPushButton *pushButton_16;
    QPushButton *pushButton_17;
    QWidget *widget_3;
    QPushButton *pushButton_15;
    QPushButton *pushButton_18;
    QPushButton *pushButton_20;
    QLabel *label_IPower_name_193;
    QComboBox *comboBox_store_type_2;
    QWidget *widget_5;
    QLabel *label_IPower_name_81;
    QLabel *label_IPower_name_106;
    QFrame *line_11;
    QLabel *label_analyze_rated_flow;
    QLabel *label_gas_produce_rated_1;
    QLabel *label_analyze_file_name;
    QLabel *label_IPower_name_125;
    QLabel *label_IPower_name_126;
    QLabel *label_analyze_rated_power;
    QLabel *label_IPower_name_171;
    QLabel *label_IPower_name_172;
    QWidget *widget_4;
    QLabel *label_analyze_standby_time;
    QLabel *label_analyze_work_time;
    QLabel *label_IPower_name_65;
    QLabel *label_IPower_name_66;
    QLabel *label_analyze_all_time;
    QLabel *label_IPower_name_55;
    QLabel *label_IPower_name_52;
    QLabel *label_IPower_name_56;
    QLabel *label_IPower_name_50;
    QLabel *label_analyze_ave_vsp;
    QLabel *label_VSP;
    QLabel *label_IPower_name_77;
    QLabel *label_acc_flow_1;
    QLabel *label_IPower_name_116;
    QLabel *label_analyze_start_time;
    QLabel *label_IPower_name_113;
    QLabel *label_IPower_name_117;
    QLabel *label_cost;
    QLabel *label_analyze_acc_flow;
    QLabel *label_analyze_acc_power;
    QLabel *label_IPower_name_112;
    QLabel *label_IPower_name_111;
    QLabel *label_IPower_name_115;
    QLabel *label_analyze_flow_cost;
    QLabel *label_IPower_name_51;
    QLabel *label_analyze_acc_charge;
    QWidget *widget_8;
    QLabel *label_IPower_name_108;
    QLabel *label_analyze_unload_power;
    QLabel *label_IPower_name_105;
    QLabel *label_IPower_name_101;
    QLabel *label_IPower_name_118;
    QLabel *label_analyze_load_charge;
    QLabel *label_analyze_loadcnt;
    QLabel *label_IPower_name_102;
    QLabel *label_IPower_name_103;
    QLabel *label_IPower_name_109;
    QLabel *label_IPower_name_121;
    QLabel *label_IPower_name_99;
    QLabel *label_IPower_name_107;
    QLabel *label_analyze_load_power_radio;
    QLabel *label_analyze_load_power;
    QLabel *label_analyze_unload_power_radio;
    QLabel *label_IPower_name_114;
    QLabel *label_IPower_name_110;
    QLabel *label_IPower_name_120;
    QLabel *label_analyze_unload_charge;
    QLabel *label_analyze_unloadcnt;
    QLabel *label_IPower_name_119;
    QLabel *label_IPower_name_173;
    QLabel *label_IPower_name_80;
    QLabel *label_IPower_name_174;
    QLabel *label_IPower_name_73;
    QLabel *label_IPower_name_78;
    QLabel *label_analyze_unload_radio;
    QLabel *label_IPower_name_75;
    QLabel *label_IPower_name_84;
    QLabel *label_analyze_loadtime;
    QLabel *label_analyze_unloadtime;
    QLabel *label_IPower_name_74;
    QLabel *label_analyze_load_radio;
    QPushButton *pushButton_11;
    QPushButton *pushButton_13;
    QPushButton *pushButton_14;
    QPushButton *pushButton_19;
    QPushButton *pushButton_5;
    QPushButton *pushButton;
    QPushButton *pushButton_2;
    QWidget *widget_2;
    QLabel *label_IPower_name;
    QLabel *label_Power_name;
    QLabel *label_power_content;
    QLabel *label_IPower_name_3;
    QLabel *label_IPower_content;
    QLabel *label_flow_content;
    QLabel *label_IPower_name_2;
    QLabel *label_IFlow_content;
    QLabel *label_IPower_name_13;
    QLabel *label_start_time_content;
    QLabel *label_IPower_name_14;
    QLabel *label_end_time_content;
    QPushButton *pushButton_6;
    QPushButton *pushButton_7;
    QLabel *label_IPower_name_46;
    QLabel *label_loding_rate_content;
    QLabel *label_Power_name_3;
    QLabel *label_power_radio_content;
    QLabel *label_IPower_name_22;
    QLabel *label_IPower_name_54;
    QLabel *label_VSP_1;
    QLabel *label_flow_unit;
    QLabel *label_acc_flow_unit;
    QLabel *label_flow_unit_3;
    QPushButton *pushButton_3;
    QPushButton *pushButton_4;
    QPushButton *pushButton_21;
    QWidget *widget_6;
    QLabel *label_IPower_name_5;
    QLabel *label_voltage_a_content;
    QLabel *label_IPower_name_6;
    QLabel *label_voltage_b_content;
    QLabel *label_IPower_name_7;
    QLabel *label_voltage_c_content;
    QLabel *label_current_c_content;
    QLabel *label_current_b_content;
    QLabel *label_current_a_content;
    QLabel *label_IPower_name_8;
    QLabel *label_IPower_name_12;
    QLabel *label_IPower_name_15;
    QLabel *label_IPower_name_16;
    QLabel *label_IPower_name_17;
    QLabel *label_IPower_name_18;
    QLabel *label_IPower_name_19;
    QLabel *label_IPower_name_20;
    QLabel *label_IPower_name_21;
    QLabel *label_frequency_content;
    QLabel *label_IPower_name_23;
    QLabel *label_power_factor_content;
    QLabel *label_IPower_name_25;
    QLabel *label_active_power_content;
    QLabel *label_IPower_name_26;
    QLabel *label_IPower_name_27;
    QLabel *label_reactive_power_content;
    QLabel *label_IPower_name_28;
    QLabel *label_IPower_name_29;
    QLabel *label_IPower_name_30;
    QLabel *label_apparent_power_content;
    QFrame *line_5;
    QPushButton *pushButton_8;
    QWidget *widget_7;
    QLabel *label_IPower_name_31;
    QLabel *label_env_temp_content;
    QLabel *label_IPower_name_32;
    QLabel *label_env_humidity_content;
    QLabel *label_IPower_name_33;
    QLabel *label_IPower_name_34;
    QLabel *label_IPower_name_35;
    QLabel *label_air_temp_content;
    QLabel *label_IPower_name_36;
    QLabel *label_air_pressure_content;
    QLabel *label_IPower_name_37;
    QLabel *label_IPower_name_38;
    QLabel *label_IPower_name_47;
    QLabel *label_IPower_name_48;
    QLabel *label_flow_content_1;
    QPushButton *pushButton_9;
    QLabel *label_flow_2;
    QLCDNumber *lcdNumber_clock;
    QPushButton *pushButton_10;
    QLabel *label_3;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->resize(1024, 601);
        QFont font;
        font.setFamily(QString::fromUtf8("ADMUI3Lg"));
        MainWindow->setFont(font);
        MainWindow->setStyleSheet(QString::fromUtf8("background-color: rgb(96, 125, 139);"));
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QString::fromUtf8("centralWidget"));
        line = new QFrame(centralWidget);
        line->setObjectName(QString::fromUtf8("line"));
        line->setGeometry(QRect(0, 80, 1024, 3));
        line->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        line->setFrameShape(QFrame::HLine);
        line->setFrameShadow(QFrame::Sunken);
        label = new QLabel(centralWidget);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(250, 15, 241, 41));
        QFont font1;
        font1.setFamily(QString::fromUtf8("\345\276\256\350\275\257\351\233\205\351\273\221"));
        font1.setPointSize(24);
        font1.setBold(false);
        font1.setWeight(50);
        label->setFont(font1);
        label_2 = new QLabel(centralWidget);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(10, 20, 200, 40));
        widget = new QWidget(centralWidget);
        widget->setObjectName(QString::fromUtf8("widget"));
        widget->setGeometry(QRect(0, 90, 931, 510));
        label_IPower_name_180 = new QLabel(widget);
        label_IPower_name_180->setObjectName(QString::fromUtf8("label_IPower_name_180"));
        label_IPower_name_180->setGeometry(QRect(500, 40, 151, 40));
        QFont font2;
        font2.setFamily(QString::fromUtf8("\345\276\256\350\275\257\351\233\205\351\273\221"));
        font2.setPointSize(22);
        label_IPower_name_180->setFont(font2);
        label_IPower_name_179 = new QLabel(widget);
        label_IPower_name_179->setObjectName(QString::fromUtf8("label_IPower_name_179"));
        label_IPower_name_179->setGeometry(QRect(140, 40, 151, 40));
        label_IPower_name_179->setFont(font2);
        label_IPower_name_181 = new QLabel(widget);
        label_IPower_name_181->setObjectName(QString::fromUtf8("label_IPower_name_181"));
        label_IPower_name_181->setGeometry(QRect(140, 105, 151, 40));
        label_IPower_name_181->setFont(font2);
        label_IPower_name_182 = new QLabel(widget);
        label_IPower_name_182->setObjectName(QString::fromUtf8("label_IPower_name_182"));
        label_IPower_name_182->setGeometry(QRect(140, 170, 151, 40));
        label_IPower_name_182->setFont(font2);
        label_IPower_name_183 = new QLabel(widget);
        label_IPower_name_183->setObjectName(QString::fromUtf8("label_IPower_name_183"));
        label_IPower_name_183->setGeometry(QRect(500, 170, 151, 40));
        label_IPower_name_183->setFont(font2);
        label_IPower_name_189 = new QLabel(widget);
        label_IPower_name_189->setObjectName(QString::fromUtf8("label_IPower_name_189"));
        label_IPower_name_189->setGeometry(QRect(110, 235, 181, 40));
        label_IPower_name_189->setFont(font2);
        label_IPower_name_190 = new QLabel(widget);
        label_IPower_name_190->setObjectName(QString::fromUtf8("label_IPower_name_190"));
        label_IPower_name_190->setGeometry(QRect(500, 235, 151, 40));
        label_IPower_name_190->setFont(font2);
        label_IPower_name_191 = new QLabel(widget);
        label_IPower_name_191->setObjectName(QString::fromUtf8("label_IPower_name_191"));
        label_IPower_name_191->setGeometry(QRect(140, 300, 151, 40));
        label_IPower_name_191->setFont(font2);
        label_IPower_name_200 = new QLabel(widget);
        label_IPower_name_200->setObjectName(QString::fromUtf8("label_IPower_name_200"));
        label_IPower_name_200->setGeometry(QRect(500, 300, 161, 40));
        label_IPower_name_200->setFont(font2);
        pushButton_12 = new QPushButton(widget);
        pushButton_12->setObjectName(QString::fromUtf8("pushButton_12"));
        pushButton_12->setGeometry(QRect(0, 40, 71, 51));
        QFont font3;
        font3.setFamily(QString::fromUtf8("\345\276\256\350\275\257\351\233\205\351\273\221"));
        font3.setPointSize(14);
        pushButton_12->setFont(font3);
        pushButton_12->setStyleSheet(QString::fromUtf8("border-image: url(:/new/prefix1/btn.qss);"));
        lineEdit_radio = new QLineEdit(widget);
        lineEdit_radio->setObjectName(QString::fromUtf8("lineEdit_radio"));
        lineEdit_radio->setGeometry(QRect(300, 40, 120, 41));
        lineEdit_radio->setFont(font2);
        lineEdit_radio->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lineEdit_radio->setMaxLength(10);
        lineEdit_charge = new QLineEdit(widget);
        lineEdit_charge->setObjectName(QString::fromUtf8("lineEdit_charge"));
        lineEdit_charge->setGeometry(QRect(300, 105, 120, 41));
        lineEdit_charge->setFont(font2);
        lineEdit_charge->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lineEdit_charge->setMaxLength(10);
        lineEdit_power = new QLineEdit(widget);
        lineEdit_power->setObjectName(QString::fromUtf8("lineEdit_power"));
        lineEdit_power->setGeometry(QRect(300, 170, 120, 41));
        lineEdit_power->setFont(font2);
        lineEdit_power->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lineEdit_power->setMaxLength(10);
        lineEdit_current_idle_max = new QLineEdit(widget);
        lineEdit_current_idle_max->setObjectName(QString::fromUtf8("lineEdit_current_idle_max"));
        lineEdit_current_idle_max->setGeometry(QRect(300, 235, 120, 41));
        lineEdit_current_idle_max->setFont(font2);
        lineEdit_current_idle_max->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lineEdit_current_idle_max->setMaxLength(10);
        lineEdit_loading_pressure = new QLineEdit(widget);
        lineEdit_loading_pressure->setObjectName(QString::fromUtf8("lineEdit_loading_pressure"));
        lineEdit_loading_pressure->setGeometry(QRect(300, 300, 120, 41));
        lineEdit_loading_pressure->setFont(font2);
        lineEdit_loading_pressure->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lineEdit_loading_pressure->setMaxLength(10);
        lineEdit_gas = new QLineEdit(widget);
        lineEdit_gas->setObjectName(QString::fromUtf8("lineEdit_gas"));
        lineEdit_gas->setGeometry(QRect(670, 170, 120, 41));
        lineEdit_gas->setFont(font2);
        lineEdit_gas->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lineEdit_gas->setMaxLength(10);
        lineEdit_current_down_max = new QLineEdit(widget);
        lineEdit_current_down_max->setObjectName(QString::fromUtf8("lineEdit_current_down_max"));
        lineEdit_current_down_max->setGeometry(QRect(670, 235, 120, 41));
        lineEdit_current_down_max->setFont(font2);
        lineEdit_current_down_max->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lineEdit_current_down_max->setMaxLength(10);
        lineEdit_unloading_pressure = new QLineEdit(widget);
        lineEdit_unloading_pressure->setObjectName(QString::fromUtf8("lineEdit_unloading_pressure"));
        lineEdit_unloading_pressure->setGeometry(QRect(670, 300, 120, 41));
        lineEdit_unloading_pressure->setFont(font2);
        lineEdit_unloading_pressure->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lineEdit_unloading_pressure->setMaxLength(10);
        comboBox_store_type = new QComboBox(widget);
        comboBox_store_type->setObjectName(QString::fromUtf8("comboBox_store_type"));
        comboBox_store_type->setGeometry(QRect(670, 100, 121, 51));
        comboBox_store_type->setFont(font2);
        comboBox_store_type->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 248, 249);"));
        comboBox_store_type->setMaxCount(3);
        label_IPower_name_184 = new QLabel(widget);
        label_IPower_name_184->setObjectName(QString::fromUtf8("label_IPower_name_184"));
        label_IPower_name_184->setGeometry(QRect(430, 105, 51, 40));
        QFont font4;
        font4.setFamily(QString::fromUtf8("\345\276\256\350\275\257\351\233\205\351\273\221"));
        font4.setPointSize(16);
        label_IPower_name_184->setFont(font4);
        label_IPower_name_185 = new QLabel(widget);
        label_IPower_name_185->setObjectName(QString::fromUtf8("label_IPower_name_185"));
        label_IPower_name_185->setGeometry(QRect(430, 170, 51, 40));
        label_IPower_name_185->setFont(font4);
        label_IPower_name_186 = new QLabel(widget);
        label_IPower_name_186->setObjectName(QString::fromUtf8("label_IPower_name_186"));
        label_IPower_name_186->setGeometry(QRect(430, 235, 51, 40));
        label_IPower_name_186->setFont(font4);
        label_IPower_name_187 = new QLabel(widget);
        label_IPower_name_187->setObjectName(QString::fromUtf8("label_IPower_name_187"));
        label_IPower_name_187->setGeometry(QRect(430, 300, 51, 40));
        label_IPower_name_187->setFont(font4);
        label_IPower_name_188 = new QLabel(widget);
        label_IPower_name_188->setObjectName(QString::fromUtf8("label_IPower_name_188"));
        label_IPower_name_188->setGeometry(QRect(800, 300, 51, 40));
        label_IPower_name_188->setFont(font4);
        label_IPower_name_192 = new QLabel(widget);
        label_IPower_name_192->setObjectName(QString::fromUtf8("label_IPower_name_192"));
        label_IPower_name_192->setGeometry(QRect(800, 235, 51, 40));
        label_IPower_name_192->setFont(font4);
        label_gas_produce_rated = new QLabel(widget);
        label_gas_produce_rated->setObjectName(QString::fromUtf8("label_gas_produce_rated"));
        label_gas_produce_rated->setGeometry(QRect(800, 170, 91, 40));
        label_gas_produce_rated->setFont(font4);
        pushButton_16 = new QPushButton(widget);
        pushButton_16->setObjectName(QString::fromUtf8("pushButton_16"));
        pushButton_16->setGeometry(QRect(0, 140, 71, 51));
        pushButton_16->setFont(font3);
        pushButton_16->setStyleSheet(QString::fromUtf8("border-image: url(:/new/prefix1/btn.qss);"));
        pushButton_17 = new QPushButton(widget);
        pushButton_17->setObjectName(QString::fromUtf8("pushButton_17"));
        pushButton_17->setGeometry(QRect(0, 210, 71, 51));
        pushButton_17->setFont(font3);
        pushButton_17->setStyleSheet(QString::fromUtf8("border-image: url(:/new/prefix1/btn.qss);"));
        widget_3 = new QWidget(widget);
        widget_3->setObjectName(QString::fromUtf8("widget_3"));
        widget_3->setGeometry(QRect(70, 0, 861, 511));
        pushButton_15 = new QPushButton(widget_3);
        pushButton_15->setObjectName(QString::fromUtf8("pushButton_15"));
        pushButton_15->setGeometry(QRect(490, 40, 181, 81));
        pushButton_15->setFont(font3);
        pushButton_15->setStyleSheet(QString::fromUtf8("border-image: url(:/new/prefix1/btn.qss);"));
        pushButton_18 = new QPushButton(widget_3);
        pushButton_18->setObjectName(QString::fromUtf8("pushButton_18"));
        pushButton_18->setGeometry(QRect(150, 40, 181, 81));
        pushButton_18->setFont(font3);
        pushButton_18->setStyleSheet(QString::fromUtf8("border-image: url(:/new/prefix1/btn.qss);"));
        pushButton_20 = new QPushButton(widget_3);
        pushButton_20->setObjectName(QString::fromUtf8("pushButton_20"));
        pushButton_20->setGeometry(QRect(150, 190, 181, 81));
        pushButton_20->setFont(font3);
        pushButton_20->setStyleSheet(QString::fromUtf8("border-image: url(:/new/prefix1/btn.qss);"));
        label_IPower_name_193 = new QLabel(widget);
        label_IPower_name_193->setObjectName(QString::fromUtf8("label_IPower_name_193"));
        label_IPower_name_193->setGeometry(QRect(500, 105, 151, 40));
        label_IPower_name_193->setFont(font2);
        comboBox_store_type_2 = new QComboBox(widget);
        comboBox_store_type_2->setObjectName(QString::fromUtf8("comboBox_store_type_2"));
        comboBox_store_type_2->setGeometry(QRect(670, 30, 121, 51));
        QFont font5;
        font5.setFamily(QString::fromUtf8("\345\276\256\350\275\257\351\233\205\351\273\221"));
        font5.setPointSize(18);
        comboBox_store_type_2->setFont(font5);
        comboBox_store_type_2->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 248, 249);"));
        comboBox_store_type_2->setMaxCount(3);
        label_IPower_name_180->raise();
        label_IPower_name_179->raise();
        label_IPower_name_181->raise();
        label_IPower_name_182->raise();
        label_IPower_name_183->raise();
        label_IPower_name_189->raise();
        label_IPower_name_190->raise();
        label_IPower_name_191->raise();
        label_IPower_name_200->raise();
        pushButton_12->raise();
        lineEdit_radio->raise();
        lineEdit_charge->raise();
        lineEdit_power->raise();
        lineEdit_current_idle_max->raise();
        lineEdit_loading_pressure->raise();
        lineEdit_gas->raise();
        lineEdit_current_down_max->raise();
        lineEdit_unloading_pressure->raise();
        comboBox_store_type->raise();
        label_IPower_name_184->raise();
        label_IPower_name_185->raise();
        label_IPower_name_186->raise();
        label_IPower_name_187->raise();
        label_IPower_name_188->raise();
        label_IPower_name_192->raise();
        label_gas_produce_rated->raise();
        pushButton_16->raise();
        pushButton_17->raise();
        label_IPower_name_193->raise();
        comboBox_store_type_2->raise();
        widget_3->raise();
        widget_5 = new QWidget(centralWidget);
        widget_5->setObjectName(QString::fromUtf8("widget_5"));
        widget_5->setGeometry(QRect(0, 90, 931, 511));
        QFont font6;
        font6.setPointSize(22);
        widget_5->setFont(font6);
        label_IPower_name_81 = new QLabel(widget_5);
        label_IPower_name_81->setObjectName(QString::fromUtf8("label_IPower_name_81"));
        label_IPower_name_81->setGeometry(QRect(860, 210, 81, 40));
        label_IPower_name_81->setFont(font3);
        label_IPower_name_106 = new QLabel(widget_5);
        label_IPower_name_106->setObjectName(QString::fromUtf8("label_IPower_name_106"));
        label_IPower_name_106->setGeometry(QRect(860, 205, 81, 40));
        label_IPower_name_106->setFont(font3);
        line_11 = new QFrame(widget_5);
        line_11->setObjectName(QString::fromUtf8("line_11"));
        line_11->setGeometry(QRect(-10, 100, 921, 16));
        line_11->setFrameShape(QFrame::HLine);
        line_11->setFrameShadow(QFrame::Sunken);
        label_analyze_rated_flow = new QLabel(widget_5);
        label_analyze_rated_flow->setObjectName(QString::fromUtf8("label_analyze_rated_flow"));
        label_analyze_rated_flow->setGeometry(QRect(680, 60, 121, 31));
        label_analyze_rated_flow->setFont(font5);
        label_analyze_rated_flow->setStyleSheet(QString::fromUtf8("background-color: rgb(193, 193, 193);"));
        label_gas_produce_rated_1 = new QLabel(widget_5);
        label_gas_produce_rated_1->setObjectName(QString::fromUtf8("label_gas_produce_rated_1"));
        label_gas_produce_rated_1->setGeometry(QRect(810, 55, 91, 40));
        label_gas_produce_rated_1->setFont(font4);
        label_analyze_file_name = new QLabel(widget_5);
        label_analyze_file_name->setObjectName(QString::fromUtf8("label_analyze_file_name"));
        label_analyze_file_name->setGeometry(QRect(250, 10, 551, 31));
        label_analyze_file_name->setFont(font5);
        label_analyze_file_name->setStyleSheet(QString::fromUtf8("background-color: rgb(193, 193, 193);"));
        label_IPower_name_125 = new QLabel(widget_5);
        label_IPower_name_125->setObjectName(QString::fromUtf8("label_IPower_name_125"));
        label_IPower_name_125->setGeometry(QRect(90, 10, 121, 40));
        label_IPower_name_125->setFont(font5);
        label_IPower_name_126 = new QLabel(widget_5);
        label_IPower_name_126->setObjectName(QString::fromUtf8("label_IPower_name_126"));
        label_IPower_name_126->setGeometry(QRect(520, 55, 141, 40));
        label_IPower_name_126->setFont(font5);
        label_analyze_rated_power = new QLabel(widget_5);
        label_analyze_rated_power->setObjectName(QString::fromUtf8("label_analyze_rated_power"));
        label_analyze_rated_power->setGeometry(QRect(250, 60, 121, 31));
        label_analyze_rated_power->setFont(font5);
        label_analyze_rated_power->setStyleSheet(QString::fromUtf8("background-color: rgb(193, 193, 193);"));
        label_IPower_name_171 = new QLabel(widget_5);
        label_IPower_name_171->setObjectName(QString::fromUtf8("label_IPower_name_171"));
        label_IPower_name_171->setGeometry(QRect(380, 55, 91, 40));
        label_IPower_name_171->setFont(font4);
        label_IPower_name_172 = new QLabel(widget_5);
        label_IPower_name_172->setObjectName(QString::fromUtf8("label_IPower_name_172"));
        label_IPower_name_172->setGeometry(QRect(90, 55, 141, 40));
        label_IPower_name_172->setFont(font5);
        widget_4 = new QWidget(widget_5);
        widget_4->setObjectName(QString::fromUtf8("widget_4"));
        widget_4->setGeometry(QRect(80, 110, 841, 401));
        label_analyze_standby_time = new QLabel(widget_4);
        label_analyze_standby_time->setObjectName(QString::fromUtf8("label_analyze_standby_time"));
        label_analyze_standby_time->setGeometry(QRect(600, 70, 161, 41));
        QFont font7;
        font7.setFamily(QString::fromUtf8("\345\276\256\350\275\257\351\233\205\351\273\221"));
        font7.setPointSize(20);
        label_analyze_standby_time->setFont(font7);
        label_analyze_standby_time->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        label_analyze_work_time = new QLabel(widget_4);
        label_analyze_work_time->setObjectName(QString::fromUtf8("label_analyze_work_time"));
        label_analyze_work_time->setGeometry(QRect(170, 70, 161, 41));
        label_analyze_work_time->setFont(font7);
        label_analyze_work_time->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        label_IPower_name_65 = new QLabel(widget_4);
        label_IPower_name_65->setObjectName(QString::fromUtf8("label_IPower_name_65"));
        label_IPower_name_65->setGeometry(QRect(770, 70, 71, 40));
        label_IPower_name_65->setFont(font4);
        label_IPower_name_66 = new QLabel(widget_4);
        label_IPower_name_66->setObjectName(QString::fromUtf8("label_IPower_name_66"));
        label_IPower_name_66->setGeometry(QRect(440, 70, 121, 40));
        label_IPower_name_66->setFont(font2);
        label_analyze_all_time = new QLabel(widget_4);
        label_analyze_all_time->setObjectName(QString::fromUtf8("label_analyze_all_time"));
        label_analyze_all_time->setGeometry(QRect(600, 10, 161, 41));
        label_analyze_all_time->setFont(font7);
        label_analyze_all_time->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        label_IPower_name_55 = new QLabel(widget_4);
        label_IPower_name_55->setObjectName(QString::fromUtf8("label_IPower_name_55"));
        label_IPower_name_55->setGeometry(QRect(340, 70, 41, 40));
        label_IPower_name_55->setFont(font4);
        label_IPower_name_52 = new QLabel(widget_4);
        label_IPower_name_52->setObjectName(QString::fromUtf8("label_IPower_name_52"));
        label_IPower_name_52->setGeometry(QRect(770, 10, 61, 40));
        label_IPower_name_52->setFont(font4);
        label_IPower_name_56 = new QLabel(widget_4);
        label_IPower_name_56->setObjectName(QString::fromUtf8("label_IPower_name_56"));
        label_IPower_name_56->setGeometry(QRect(10, 70, 121, 40));
        label_IPower_name_56->setFont(font2);
        label_IPower_name_50 = new QLabel(widget_4);
        label_IPower_name_50->setObjectName(QString::fromUtf8("label_IPower_name_50"));
        label_IPower_name_50->setGeometry(QRect(440, 10, 121, 40));
        label_IPower_name_50->setFont(font2);
        label_analyze_ave_vsp = new QLabel(widget_4);
        label_analyze_ave_vsp->setObjectName(QString::fromUtf8("label_analyze_ave_vsp"));
        label_analyze_ave_vsp->setGeometry(QRect(170, 250, 161, 41));
        label_analyze_ave_vsp->setFont(font7);
        label_analyze_ave_vsp->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        label_VSP = new QLabel(widget_4);
        label_VSP->setObjectName(QString::fromUtf8("label_VSP"));
        label_VSP->setGeometry(QRect(340, 250, 141, 40));
        label_VSP->setFont(font4);
        label_IPower_name_77 = new QLabel(widget_4);
        label_IPower_name_77->setObjectName(QString::fromUtf8("label_IPower_name_77"));
        label_IPower_name_77->setGeometry(QRect(10, 250, 151, 40));
        label_IPower_name_77->setFont(font2);
        label_acc_flow_1 = new QLabel(widget_4);
        label_acc_flow_1->setObjectName(QString::fromUtf8("label_acc_flow_1"));
        label_acc_flow_1->setGeometry(QRect(340, 130, 41, 40));
        label_acc_flow_1->setFont(font3);
        label_IPower_name_116 = new QLabel(widget_4);
        label_IPower_name_116->setObjectName(QString::fromUtf8("label_IPower_name_116"));
        label_IPower_name_116->setGeometry(QRect(10, 190, 131, 40));
        label_IPower_name_116->setFont(font2);
        label_analyze_start_time = new QLabel(widget_4);
        label_analyze_start_time->setObjectName(QString::fromUtf8("label_analyze_start_time"));
        label_analyze_start_time->setGeometry(QRect(170, 10, 251, 41));
        label_analyze_start_time->setFont(font5);
        label_analyze_start_time->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        label_IPower_name_113 = new QLabel(widget_4);
        label_IPower_name_113->setObjectName(QString::fromUtf8("label_IPower_name_113"));
        label_IPower_name_113->setGeometry(QRect(440, 130, 121, 40));
        label_IPower_name_113->setFont(font2);
        label_IPower_name_117 = new QLabel(widget_4);
        label_IPower_name_117->setObjectName(QString::fromUtf8("label_IPower_name_117"));
        label_IPower_name_117->setGeometry(QRect(440, 190, 131, 40));
        label_IPower_name_117->setFont(font2);
        label_cost = new QLabel(widget_4);
        label_cost->setObjectName(QString::fromUtf8("label_cost"));
        label_cost->setGeometry(QRect(770, 190, 61, 40));
        label_cost->setFont(font3);
        label_analyze_acc_flow = new QLabel(widget_4);
        label_analyze_acc_flow->setObjectName(QString::fromUtf8("label_analyze_acc_flow"));
        label_analyze_acc_flow->setGeometry(QRect(170, 130, 161, 41));
        label_analyze_acc_flow->setFont(font7);
        label_analyze_acc_flow->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        label_analyze_acc_power = new QLabel(widget_4);
        label_analyze_acc_power->setObjectName(QString::fromUtf8("label_analyze_acc_power"));
        label_analyze_acc_power->setGeometry(QRect(600, 130, 161, 41));
        label_analyze_acc_power->setFont(font7);
        label_analyze_acc_power->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        label_IPower_name_112 = new QLabel(widget_4);
        label_IPower_name_112->setObjectName(QString::fromUtf8("label_IPower_name_112"));
        label_IPower_name_112->setGeometry(QRect(10, 130, 131, 40));
        label_IPower_name_112->setFont(font2);
        label_IPower_name_111 = new QLabel(widget_4);
        label_IPower_name_111->setObjectName(QString::fromUtf8("label_IPower_name_111"));
        label_IPower_name_111->setGeometry(QRect(770, 130, 81, 40));
        label_IPower_name_111->setFont(font3);
        label_IPower_name_115 = new QLabel(widget_4);
        label_IPower_name_115->setObjectName(QString::fromUtf8("label_IPower_name_115"));
        label_IPower_name_115->setGeometry(QRect(341, 190, 61, 40));
        label_IPower_name_115->setFont(font3);
        label_analyze_flow_cost = new QLabel(widget_4);
        label_analyze_flow_cost->setObjectName(QString::fromUtf8("label_analyze_flow_cost"));
        label_analyze_flow_cost->setGeometry(QRect(600, 190, 161, 41));
        label_analyze_flow_cost->setFont(font7);
        label_analyze_flow_cost->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        label_IPower_name_51 = new QLabel(widget_4);
        label_IPower_name_51->setObjectName(QString::fromUtf8("label_IPower_name_51"));
        label_IPower_name_51->setGeometry(QRect(10, 10, 121, 40));
        label_IPower_name_51->setFont(font2);
        label_analyze_acc_charge = new QLabel(widget_4);
        label_analyze_acc_charge->setObjectName(QString::fromUtf8("label_analyze_acc_charge"));
        label_analyze_acc_charge->setGeometry(QRect(170, 190, 161, 41));
        label_analyze_acc_charge->setFont(font7);
        label_analyze_acc_charge->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        widget_8 = new QWidget(widget_5);
        widget_8->setObjectName(QString::fromUtf8("widget_8"));
        widget_8->setGeometry(QRect(80, 110, 841, 401));
        label_IPower_name_108 = new QLabel(widget_8);
        label_IPower_name_108->setObjectName(QString::fromUtf8("label_IPower_name_108"));
        label_IPower_name_108->setGeometry(QRect(440, 130, 121, 40));
        label_IPower_name_108->setFont(font2);
        label_analyze_unload_power = new QLabel(widget_8);
        label_analyze_unload_power->setObjectName(QString::fromUtf8("label_analyze_unload_power"));
        label_analyze_unload_power->setGeometry(QRect(600, 190, 161, 41));
        label_analyze_unload_power->setFont(font7);
        label_analyze_unload_power->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        label_IPower_name_105 = new QLabel(widget_8);
        label_IPower_name_105->setObjectName(QString::fromUtf8("label_IPower_name_105"));
        label_IPower_name_105->setGeometry(QRect(440, 190, 151, 40));
        label_IPower_name_105->setFont(font2);
        label_IPower_name_101 = new QLabel(widget_8);
        label_IPower_name_101->setObjectName(QString::fromUtf8("label_IPower_name_101"));
        label_IPower_name_101->setGeometry(QRect(340, 190, 81, 40));
        label_IPower_name_101->setFont(font3);
        label_IPower_name_118 = new QLabel(widget_8);
        label_IPower_name_118->setObjectName(QString::fromUtf8("label_IPower_name_118"));
        label_IPower_name_118->setGeometry(QRect(770, 310, 81, 40));
        label_IPower_name_118->setFont(font3);
        label_analyze_load_charge = new QLabel(widget_8);
        label_analyze_load_charge->setObjectName(QString::fromUtf8("label_analyze_load_charge"));
        label_analyze_load_charge->setGeometry(QRect(170, 250, 161, 41));
        label_analyze_load_charge->setFont(font7);
        label_analyze_load_charge->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        label_analyze_loadcnt = new QLabel(widget_8);
        label_analyze_loadcnt->setObjectName(QString::fromUtf8("label_analyze_loadcnt"));
        label_analyze_loadcnt->setGeometry(QRect(170, 130, 161, 41));
        label_analyze_loadcnt->setFont(font7);
        label_analyze_loadcnt->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        label_IPower_name_102 = new QLabel(widget_8);
        label_IPower_name_102->setObjectName(QString::fromUtf8("label_IPower_name_102"));
        label_IPower_name_102->setGeometry(QRect(340, 250, 81, 40));
        label_IPower_name_102->setFont(font3);
        label_IPower_name_103 = new QLabel(widget_8);
        label_IPower_name_103->setObjectName(QString::fromUtf8("label_IPower_name_103"));
        label_IPower_name_103->setGeometry(QRect(10, 250, 131, 40));
        label_IPower_name_103->setFont(font2);
        label_IPower_name_109 = new QLabel(widget_8);
        label_IPower_name_109->setObjectName(QString::fromUtf8("label_IPower_name_109"));
        label_IPower_name_109->setGeometry(QRect(770, 250, 81, 40));
        label_IPower_name_109->setFont(font3);
        label_IPower_name_121 = new QLabel(widget_8);
        label_IPower_name_121->setObjectName(QString::fromUtf8("label_IPower_name_121"));
        label_IPower_name_121->setGeometry(QRect(440, 300, 221, 71));
        label_IPower_name_121->setFont(font7);
        label_IPower_name_99 = new QLabel(widget_8);
        label_IPower_name_99->setObjectName(QString::fromUtf8("label_IPower_name_99"));
        label_IPower_name_99->setGeometry(QRect(10, 190, 131, 40));
        label_IPower_name_99->setFont(font2);
        label_IPower_name_107 = new QLabel(widget_8);
        label_IPower_name_107->setObjectName(QString::fromUtf8("label_IPower_name_107"));
        label_IPower_name_107->setGeometry(QRect(440, 250, 131, 40));
        label_IPower_name_107->setFont(font2);
        label_analyze_load_power_radio = new QLabel(widget_8);
        label_analyze_load_power_radio->setObjectName(QString::fromUtf8("label_analyze_load_power_radio"));
        label_analyze_load_power_radio->setGeometry(QRect(170, 310, 161, 41));
        label_analyze_load_power_radio->setFont(font7);
        label_analyze_load_power_radio->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        label_analyze_load_power = new QLabel(widget_8);
        label_analyze_load_power->setObjectName(QString::fromUtf8("label_analyze_load_power"));
        label_analyze_load_power->setGeometry(QRect(170, 190, 161, 41));
        label_analyze_load_power->setFont(font7);
        label_analyze_load_power->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        label_analyze_unload_power_radio = new QLabel(widget_8);
        label_analyze_unload_power_radio->setObjectName(QString::fromUtf8("label_analyze_unload_power_radio"));
        label_analyze_unload_power_radio->setGeometry(QRect(600, 310, 161, 41));
        label_analyze_unload_power_radio->setFont(font7);
        label_analyze_unload_power_radio->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        label_IPower_name_114 = new QLabel(widget_8);
        label_IPower_name_114->setObjectName(QString::fromUtf8("label_IPower_name_114"));
        label_IPower_name_114->setGeometry(QRect(10, 130, 131, 40));
        label_IPower_name_114->setFont(font2);
        label_IPower_name_110 = new QLabel(widget_8);
        label_IPower_name_110->setObjectName(QString::fromUtf8("label_IPower_name_110"));
        label_IPower_name_110->setGeometry(QRect(770, 190, 81, 40));
        label_IPower_name_110->setFont(font3);
        label_IPower_name_120 = new QLabel(widget_8);
        label_IPower_name_120->setObjectName(QString::fromUtf8("label_IPower_name_120"));
        label_IPower_name_120->setGeometry(QRect(10, 300, 151, 71));
        label_IPower_name_120->setFont(font7);
        label_analyze_unload_charge = new QLabel(widget_8);
        label_analyze_unload_charge->setObjectName(QString::fromUtf8("label_analyze_unload_charge"));
        label_analyze_unload_charge->setGeometry(QRect(600, 250, 161, 41));
        label_analyze_unload_charge->setFont(font7);
        label_analyze_unload_charge->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        label_analyze_unloadcnt = new QLabel(widget_8);
        label_analyze_unloadcnt->setObjectName(QString::fromUtf8("label_analyze_unloadcnt"));
        label_analyze_unloadcnt->setGeometry(QRect(600, 130, 161, 41));
        label_analyze_unloadcnt->setFont(font7);
        label_analyze_unloadcnt->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        label_IPower_name_119 = new QLabel(widget_8);
        label_IPower_name_119->setObjectName(QString::fromUtf8("label_IPower_name_119"));
        label_IPower_name_119->setGeometry(QRect(340, 310, 41, 40));
        label_IPower_name_119->setFont(font3);
        label_IPower_name_173 = new QLabel(widget_8);
        label_IPower_name_173->setObjectName(QString::fromUtf8("label_IPower_name_173"));
        label_IPower_name_173->setGeometry(QRect(340, 70, 81, 40));
        label_IPower_name_173->setFont(font4);
        label_IPower_name_80 = new QLabel(widget_8);
        label_IPower_name_80->setObjectName(QString::fromUtf8("label_IPower_name_80"));
        label_IPower_name_80->setGeometry(QRect(440, 70, 131, 40));
        label_IPower_name_80->setFont(font2);
        label_IPower_name_174 = new QLabel(widget_8);
        label_IPower_name_174->setObjectName(QString::fromUtf8("label_IPower_name_174"));
        label_IPower_name_174->setGeometry(QRect(770, 70, 81, 40));
        label_IPower_name_174->setFont(font4);
        label_IPower_name_73 = new QLabel(widget_8);
        label_IPower_name_73->setObjectName(QString::fromUtf8("label_IPower_name_73"));
        label_IPower_name_73->setGeometry(QRect(340, 10, 81, 40));
        label_IPower_name_73->setFont(font4);
        label_IPower_name_78 = new QLabel(widget_8);
        label_IPower_name_78->setObjectName(QString::fromUtf8("label_IPower_name_78"));
        label_IPower_name_78->setGeometry(QRect(10, 10, 121, 40));
        label_IPower_name_78->setFont(font2);
        label_analyze_unload_radio = new QLabel(widget_8);
        label_analyze_unload_radio->setObjectName(QString::fromUtf8("label_analyze_unload_radio"));
        label_analyze_unload_radio->setGeometry(QRect(600, 70, 161, 41));
        label_analyze_unload_radio->setFont(font7);
        label_analyze_unload_radio->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        label_IPower_name_75 = new QLabel(widget_8);
        label_IPower_name_75->setObjectName(QString::fromUtf8("label_IPower_name_75"));
        label_IPower_name_75->setGeometry(QRect(770, 10, 81, 40));
        label_IPower_name_75->setFont(font4);
        label_IPower_name_84 = new QLabel(widget_8);
        label_IPower_name_84->setObjectName(QString::fromUtf8("label_IPower_name_84"));
        label_IPower_name_84->setGeometry(QRect(10, 70, 111, 40));
        label_IPower_name_84->setFont(font2);
        label_analyze_loadtime = new QLabel(widget_8);
        label_analyze_loadtime->setObjectName(QString::fromUtf8("label_analyze_loadtime"));
        label_analyze_loadtime->setGeometry(QRect(170, 10, 161, 41));
        label_analyze_loadtime->setFont(font7);
        label_analyze_loadtime->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        label_analyze_unloadtime = new QLabel(widget_8);
        label_analyze_unloadtime->setObjectName(QString::fromUtf8("label_analyze_unloadtime"));
        label_analyze_unloadtime->setGeometry(QRect(600, 10, 161, 41));
        label_analyze_unloadtime->setFont(font7);
        label_analyze_unloadtime->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        label_IPower_name_74 = new QLabel(widget_8);
        label_IPower_name_74->setObjectName(QString::fromUtf8("label_IPower_name_74"));
        label_IPower_name_74->setGeometry(QRect(440, 10, 121, 40));
        label_IPower_name_74->setFont(font2);
        label_analyze_load_radio = new QLabel(widget_8);
        label_analyze_load_radio->setObjectName(QString::fromUtf8("label_analyze_load_radio"));
        label_analyze_load_radio->setGeometry(QRect(170, 70, 161, 41));
        label_analyze_load_radio->setFont(font7);
        label_analyze_load_radio->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        pushButton_11 = new QPushButton(widget_5);
        pushButton_11->setObjectName(QString::fromUtf8("pushButton_11"));
        pushButton_11->setGeometry(QRect(0, 120, 71, 51));
        pushButton_11->setFont(font3);
        pushButton_11->setStyleSheet(QString::fromUtf8("border-image: url(:/new/prefix1/btn.qss);"));
        pushButton_13 = new QPushButton(widget_5);
        pushButton_13->setObjectName(QString::fromUtf8("pushButton_13"));
        pushButton_13->setGeometry(QRect(0, 190, 71, 51));
        pushButton_13->setFont(font3);
        pushButton_13->setStyleSheet(QString::fromUtf8("border-image: url(:/new/prefix1/btn.qss);"));
        pushButton_14 = new QPushButton(widget_5);
        pushButton_14->setObjectName(QString::fromUtf8("pushButton_14"));
        pushButton_14->setGeometry(QRect(0, 10, 71, 51));
        pushButton_14->setFont(font3);
        pushButton_14->setStyleSheet(QString::fromUtf8("border-image: url(:/new/prefix1/btn.qss);"));
        pushButton_19 = new QPushButton(widget_5);
        pushButton_19->setObjectName(QString::fromUtf8("pushButton_19"));
        pushButton_19->setGeometry(QRect(0, 410, 71, 51));
        pushButton_19->setFont(font3);
        pushButton_19->setStyleSheet(QString::fromUtf8("border-image: url(:/new/prefix1/btn.qss);"));
        label_IPower_name_81->raise();
        label_IPower_name_106->raise();
        line_11->raise();
        label_analyze_rated_flow->raise();
        label_gas_produce_rated_1->raise();
        label_analyze_file_name->raise();
        label_IPower_name_125->raise();
        label_IPower_name_126->raise();
        label_analyze_rated_power->raise();
        label_IPower_name_171->raise();
        label_IPower_name_172->raise();
        pushButton_11->raise();
        pushButton_13->raise();
        pushButton_14->raise();
        widget_4->raise();
        widget_8->raise();
        pushButton_19->raise();
        pushButton_5 = new QPushButton(centralWidget);
        pushButton_5->setObjectName(QString::fromUtf8("pushButton_5"));
        pushButton_5->setGeometry(QRect(930, 390, 100, 81));
        pushButton_5->setFont(font3);
        pushButton = new QPushButton(centralWidget);
        pushButton->setObjectName(QString::fromUtf8("pushButton"));
        pushButton->setGeometry(QRect(930, 130, 100, 81));
        pushButton->setFont(font3);
        pushButton->setStyleSheet(QString::fromUtf8("border-image: url(:/new/prefix1/btn.qss);"));
        pushButton_2 = new QPushButton(centralWidget);
        pushButton_2->setObjectName(QString::fromUtf8("pushButton_2"));
        pushButton_2->setGeometry(QRect(930, 260, 100, 81));
        pushButton_2->setFont(font3);
        widget_2 = new QWidget(centralWidget);
        widget_2->setObjectName(QString::fromUtf8("widget_2"));
        widget_2->setGeometry(QRect(0, 90, 931, 510));
        QFont font8;
        font8.setPointSize(18);
        widget_2->setFont(font8);
        label_IPower_name = new QLabel(widget_2);
        label_IPower_name->setObjectName(QString::fromUtf8("label_IPower_name"));
        label_IPower_name->setGeometry(QRect(100, 230, 121, 40));
        label_IPower_name->setFont(font2);
        label_Power_name = new QLabel(widget_2);
        label_Power_name->setObjectName(QString::fromUtf8("label_Power_name"));
        label_Power_name->setGeometry(QRect(100, 370, 121, 40));
        label_Power_name->setFont(font2);
        label_power_content = new QLabel(widget_2);
        label_power_content->setObjectName(QString::fromUtf8("label_power_content"));
        label_power_content->setGeometry(QRect(230, 370, 151, 41));
        label_power_content->setFont(font7);
        label_power_content->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        label_IPower_name_3 = new QLabel(widget_2);
        label_IPower_name_3->setObjectName(QString::fromUtf8("label_IPower_name_3"));
        label_IPower_name_3->setGeometry(QRect(540, 370, 121, 40));
        label_IPower_name_3->setFont(font2);
        label_IPower_content = new QLabel(widget_2);
        label_IPower_content->setObjectName(QString::fromUtf8("label_IPower_content"));
        label_IPower_content->setGeometry(QRect(230, 230, 151, 41));
        label_IPower_content->setFont(font7);
        label_IPower_content->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        label_flow_content = new QLabel(widget_2);
        label_flow_content->setObjectName(QString::fromUtf8("label_flow_content"));
        label_flow_content->setGeometry(QRect(670, 370, 151, 41));
        label_flow_content->setFont(font7);
        label_flow_content->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        label_IPower_name_2 = new QLabel(widget_2);
        label_IPower_name_2->setObjectName(QString::fromUtf8("label_IPower_name_2"));
        label_IPower_name_2->setGeometry(QRect(540, 230, 121, 40));
        label_IPower_name_2->setFont(font2);
        label_IFlow_content = new QLabel(widget_2);
        label_IFlow_content->setObjectName(QString::fromUtf8("label_IFlow_content"));
        label_IFlow_content->setGeometry(QRect(670, 230, 151, 41));
        label_IFlow_content->setFont(font7);
        label_IFlow_content->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        label_IPower_name_13 = new QLabel(widget_2);
        label_IPower_name_13->setObjectName(QString::fromUtf8("label_IPower_name_13"));
        label_IPower_name_13->setGeometry(QRect(100, 440, 121, 40));
        label_IPower_name_13->setFont(font2);
        label_start_time_content = new QLabel(widget_2);
        label_start_time_content->setObjectName(QString::fromUtf8("label_start_time_content"));
        label_start_time_content->setGeometry(QRect(230, 440, 241, 41));
        label_start_time_content->setFont(font5);
        label_start_time_content->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        label_IPower_name_14 = new QLabel(widget_2);
        label_IPower_name_14->setObjectName(QString::fromUtf8("label_IPower_name_14"));
        label_IPower_name_14->setGeometry(QRect(540, 440, 121, 40));
        label_IPower_name_14->setFont(font2);
        label_end_time_content = new QLabel(widget_2);
        label_end_time_content->setObjectName(QString::fromUtf8("label_end_time_content"));
        label_end_time_content->setGeometry(QRect(670, 440, 241, 41));
        label_end_time_content->setFont(font5);
        label_end_time_content->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        pushButton_6 = new QPushButton(widget_2);
        pushButton_6->setObjectName(QString::fromUtf8("pushButton_6"));
        pushButton_6->setGeometry(QRect(0, 40, 81, 61));
        pushButton_6->setFont(font3);
        pushButton_6->setStyleSheet(QString::fromUtf8("border-image: url(:/new/prefix1/btn.qss);"));
        pushButton_7 = new QPushButton(widget_2);
        pushButton_7->setObjectName(QString::fromUtf8("pushButton_7"));
        pushButton_7->setGeometry(QRect(0, 130, 81, 61));
        pushButton_7->setFont(font3);
        pushButton_7->setStyleSheet(QString::fromUtf8("border-image: url(:/new/prefix1/btn.qss);"));
        label_IPower_name_46 = new QLabel(widget_2);
        label_IPower_name_46->setObjectName(QString::fromUtf8("label_IPower_name_46"));
        label_IPower_name_46->setGeometry(QRect(540, 300, 121, 40));
        label_IPower_name_46->setFont(font2);
        label_loding_rate_content = new QLabel(widget_2);
        label_loding_rate_content->setObjectName(QString::fromUtf8("label_loding_rate_content"));
        label_loding_rate_content->setGeometry(QRect(670, 300, 151, 41));
        label_loding_rate_content->setFont(font7);
        label_loding_rate_content->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        label_Power_name_3 = new QLabel(widget_2);
        label_Power_name_3->setObjectName(QString::fromUtf8("label_Power_name_3"));
        label_Power_name_3->setGeometry(QRect(100, 300, 131, 40));
        label_Power_name_3->setFont(font2);
        label_power_radio_content = new QLabel(widget_2);
        label_power_radio_content->setObjectName(QString::fromUtf8("label_power_radio_content"));
        label_power_radio_content->setGeometry(QRect(230, 300, 151, 41));
        label_power_radio_content->setFont(font7);
        label_power_radio_content->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        label_IPower_name_22 = new QLabel(widget_2);
        label_IPower_name_22->setObjectName(QString::fromUtf8("label_IPower_name_22"));
        label_IPower_name_22->setGeometry(QRect(390, 230, 51, 40));
        label_IPower_name_22->setFont(font4);
        label_IPower_name_54 = new QLabel(widget_2);
        label_IPower_name_54->setObjectName(QString::fromUtf8("label_IPower_name_54"));
        label_IPower_name_54->setGeometry(QRect(390, 370, 51, 40));
        label_IPower_name_54->setFont(font4);
        label_VSP_1 = new QLabel(widget_2);
        label_VSP_1->setObjectName(QString::fromUtf8("label_VSP_1"));
        label_VSP_1->setGeometry(QRect(390, 300, 131, 40));
        label_VSP_1->setFont(font4);
        label_flow_unit = new QLabel(widget_2);
        label_flow_unit->setObjectName(QString::fromUtf8("label_flow_unit"));
        label_flow_unit->setGeometry(QRect(830, 230, 91, 40));
        label_flow_unit->setFont(font4);
        label_acc_flow_unit = new QLabel(widget_2);
        label_acc_flow_unit->setObjectName(QString::fromUtf8("label_acc_flow_unit"));
        label_acc_flow_unit->setGeometry(QRect(830, 370, 51, 40));
        label_acc_flow_unit->setFont(font4);
        label_flow_unit_3 = new QLabel(widget_2);
        label_flow_unit_3->setObjectName(QString::fromUtf8("label_flow_unit_3"));
        label_flow_unit_3->setGeometry(QRect(830, 300, 51, 40));
        label_flow_unit_3->setFont(font4);
        pushButton_3 = new QPushButton(widget_2);
        pushButton_3->setObjectName(QString::fromUtf8("pushButton_3"));
        pushButton_3->setGeometry(QRect(0, 220, 81, 61));
        pushButton_3->setFont(font3);
        pushButton_4 = new QPushButton(widget_2);
        pushButton_4->setObjectName(QString::fromUtf8("pushButton_4"));
        pushButton_4->setGeometry(QRect(0, 310, 81, 61));
        pushButton_4->setFont(font3);
        pushButton_21 = new QPushButton(widget_2);
        pushButton_21->setObjectName(QString::fromUtf8("pushButton_21"));
        pushButton_21->setGeometry(QRect(0, 450, 81, 61));
        pushButton_21->setFont(font3);
        label_IPower_name->raise();
        label_Power_name->raise();
        label_power_content->raise();
        label_IPower_name_3->raise();
        label_flow_content->raise();
        label_IPower_name_2->raise();
        label_IFlow_content->raise();
        label_IPower_name_13->raise();
        label_start_time_content->raise();
        label_IPower_name_14->raise();
        label_end_time_content->raise();
        pushButton_6->raise();
        pushButton_7->raise();
        label_IPower_name_46->raise();
        label_loding_rate_content->raise();
        label_Power_name_3->raise();
        label_power_radio_content->raise();
        label_IPower_content->raise();
        label_IPower_name_22->raise();
        label_IPower_name_54->raise();
        label_VSP_1->raise();
        label_flow_unit->raise();
        label_acc_flow_unit->raise();
        label_flow_unit_3->raise();
        pushButton_3->raise();
        pushButton_4->raise();
        pushButton_21->raise();
        widget_6 = new QWidget(centralWidget);
        widget_6->setObjectName(QString::fromUtf8("widget_6"));
        widget_6->setGeometry(QRect(0, 90, 900, 510));
        label_IPower_name_5 = new QLabel(widget_6);
        label_IPower_name_5->setObjectName(QString::fromUtf8("label_IPower_name_5"));
        label_IPower_name_5->setGeometry(QRect(170, 70, 51, 40));
        label_IPower_name_5->setFont(font2);
        label_voltage_a_content = new QLabel(widget_6);
        label_voltage_a_content->setObjectName(QString::fromUtf8("label_voltage_a_content"));
        label_voltage_a_content->setGeometry(QRect(240, 70, 151, 41));
        label_voltage_a_content->setFont(font5);
        label_voltage_a_content->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        label_IPower_name_6 = new QLabel(widget_6);
        label_IPower_name_6->setObjectName(QString::fromUtf8("label_IPower_name_6"));
        label_IPower_name_6->setGeometry(QRect(170, 130, 51, 40));
        label_IPower_name_6->setFont(font2);
        label_voltage_b_content = new QLabel(widget_6);
        label_voltage_b_content->setObjectName(QString::fromUtf8("label_voltage_b_content"));
        label_voltage_b_content->setGeometry(QRect(240, 130, 151, 41));
        label_voltage_b_content->setFont(font5);
        label_voltage_b_content->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        label_IPower_name_7 = new QLabel(widget_6);
        label_IPower_name_7->setObjectName(QString::fromUtf8("label_IPower_name_7"));
        label_IPower_name_7->setGeometry(QRect(170, 190, 51, 40));
        label_IPower_name_7->setFont(font2);
        label_voltage_c_content = new QLabel(widget_6);
        label_voltage_c_content->setObjectName(QString::fromUtf8("label_voltage_c_content"));
        label_voltage_c_content->setGeometry(QRect(240, 190, 151, 41));
        label_voltage_c_content->setFont(font5);
        label_voltage_c_content->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        label_current_c_content = new QLabel(widget_6);
        label_current_c_content->setObjectName(QString::fromUtf8("label_current_c_content"));
        label_current_c_content->setGeometry(QRect(620, 190, 151, 41));
        label_current_c_content->setFont(font5);
        label_current_c_content->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        label_current_b_content = new QLabel(widget_6);
        label_current_b_content->setObjectName(QString::fromUtf8("label_current_b_content"));
        label_current_b_content->setGeometry(QRect(620, 130, 151, 41));
        label_current_b_content->setFont(font5);
        label_current_b_content->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        label_current_a_content = new QLabel(widget_6);
        label_current_a_content->setObjectName(QString::fromUtf8("label_current_a_content"));
        label_current_a_content->setGeometry(QRect(620, 70, 151, 41));
        label_current_a_content->setFont(font5);
        label_current_a_content->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        label_IPower_name_8 = new QLabel(widget_6);
        label_IPower_name_8->setObjectName(QString::fromUtf8("label_IPower_name_8"));
        label_IPower_name_8->setGeometry(QRect(280, 10, 61, 40));
        label_IPower_name_8->setFont(font2);
        label_IPower_name_12 = new QLabel(widget_6);
        label_IPower_name_12->setObjectName(QString::fromUtf8("label_IPower_name_12"));
        label_IPower_name_12->setGeometry(QRect(660, 10, 61, 40));
        label_IPower_name_12->setFont(font2);
        label_IPower_name_15 = new QLabel(widget_6);
        label_IPower_name_15->setObjectName(QString::fromUtf8("label_IPower_name_15"));
        label_IPower_name_15->setGeometry(QRect(400, 70, 41, 40));
        label_IPower_name_15->setFont(font5);
        label_IPower_name_16 = new QLabel(widget_6);
        label_IPower_name_16->setObjectName(QString::fromUtf8("label_IPower_name_16"));
        label_IPower_name_16->setGeometry(QRect(400, 130, 41, 40));
        label_IPower_name_16->setFont(font5);
        label_IPower_name_17 = new QLabel(widget_6);
        label_IPower_name_17->setObjectName(QString::fromUtf8("label_IPower_name_17"));
        label_IPower_name_17->setGeometry(QRect(400, 190, 41, 40));
        label_IPower_name_17->setFont(font5);
        label_IPower_name_18 = new QLabel(widget_6);
        label_IPower_name_18->setObjectName(QString::fromUtf8("label_IPower_name_18"));
        label_IPower_name_18->setGeometry(QRect(780, 70, 41, 40));
        label_IPower_name_18->setFont(font5);
        label_IPower_name_19 = new QLabel(widget_6);
        label_IPower_name_19->setObjectName(QString::fromUtf8("label_IPower_name_19"));
        label_IPower_name_19->setGeometry(QRect(780, 130, 41, 40));
        label_IPower_name_19->setFont(font5);
        label_IPower_name_20 = new QLabel(widget_6);
        label_IPower_name_20->setObjectName(QString::fromUtf8("label_IPower_name_20"));
        label_IPower_name_20->setGeometry(QRect(780, 190, 41, 40));
        label_IPower_name_20->setFont(font5);
        label_IPower_name_21 = new QLabel(widget_6);
        label_IPower_name_21->setObjectName(QString::fromUtf8("label_IPower_name_21"));
        label_IPower_name_21->setGeometry(QRect(100, 305, 111, 40));
        label_IPower_name_21->setFont(font2);
        label_frequency_content = new QLabel(widget_6);
        label_frequency_content->setObjectName(QString::fromUtf8("label_frequency_content"));
        label_frequency_content->setGeometry(QRect(240, 305, 151, 41));
        label_frequency_content->setFont(font5);
        label_frequency_content->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        label_IPower_name_23 = new QLabel(widget_6);
        label_IPower_name_23->setObjectName(QString::fromUtf8("label_IPower_name_23"));
        label_IPower_name_23->setGeometry(QRect(480, 305, 121, 40));
        label_IPower_name_23->setFont(font2);
        label_power_factor_content = new QLabel(widget_6);
        label_power_factor_content->setObjectName(QString::fromUtf8("label_power_factor_content"));
        label_power_factor_content->setGeometry(QRect(620, 305, 151, 41));
        label_power_factor_content->setFont(font5);
        label_power_factor_content->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        label_IPower_name_25 = new QLabel(widget_6);
        label_IPower_name_25->setObjectName(QString::fromUtf8("label_IPower_name_25"));
        label_IPower_name_25->setGeometry(QRect(100, 360, 121, 40));
        label_IPower_name_25->setFont(font2);
        label_active_power_content = new QLabel(widget_6);
        label_active_power_content->setObjectName(QString::fromUtf8("label_active_power_content"));
        label_active_power_content->setGeometry(QRect(240, 360, 151, 41));
        label_active_power_content->setFont(font5);
        label_active_power_content->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        label_IPower_name_26 = new QLabel(widget_6);
        label_IPower_name_26->setObjectName(QString::fromUtf8("label_IPower_name_26"));
        label_IPower_name_26->setGeometry(QRect(400, 360, 41, 40));
        label_IPower_name_26->setFont(font5);
        label_IPower_name_27 = new QLabel(widget_6);
        label_IPower_name_27->setObjectName(QString::fromUtf8("label_IPower_name_27"));
        label_IPower_name_27->setGeometry(QRect(480, 360, 121, 40));
        label_IPower_name_27->setFont(font2);
        label_reactive_power_content = new QLabel(widget_6);
        label_reactive_power_content->setObjectName(QString::fromUtf8("label_reactive_power_content"));
        label_reactive_power_content->setGeometry(QRect(620, 360, 151, 41));
        label_reactive_power_content->setFont(font5);
        label_reactive_power_content->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        label_IPower_name_28 = new QLabel(widget_6);
        label_IPower_name_28->setObjectName(QString::fromUtf8("label_IPower_name_28"));
        label_IPower_name_28->setGeometry(QRect(780, 360, 61, 40));
        label_IPower_name_28->setFont(font5);
        label_IPower_name_29 = new QLabel(widget_6);
        label_IPower_name_29->setObjectName(QString::fromUtf8("label_IPower_name_29"));
        label_IPower_name_29->setGeometry(QRect(400, 415, 51, 40));
        label_IPower_name_29->setFont(font5);
        label_IPower_name_30 = new QLabel(widget_6);
        label_IPower_name_30->setObjectName(QString::fromUtf8("label_IPower_name_30"));
        label_IPower_name_30->setGeometry(QRect(100, 415, 121, 40));
        label_IPower_name_30->setFont(font2);
        label_apparent_power_content = new QLabel(widget_6);
        label_apparent_power_content->setObjectName(QString::fromUtf8("label_apparent_power_content"));
        label_apparent_power_content->setGeometry(QRect(240, 415, 151, 41));
        label_apparent_power_content->setFont(font5);
        label_apparent_power_content->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        line_5 = new QFrame(widget_6);
        line_5->setObjectName(QString::fromUtf8("line_5"));
        line_5->setGeometry(QRect(0, 270, 921, 16));
        line_5->setFrameShape(QFrame::HLine);
        line_5->setFrameShadow(QFrame::Sunken);
        pushButton_8 = new QPushButton(widget_6);
        pushButton_8->setObjectName(QString::fromUtf8("pushButton_8"));
        pushButton_8->setGeometry(QRect(0, 40, 81, 61));
        pushButton_8->setFont(font3);
        pushButton_8->setStyleSheet(QString::fromUtf8("border-image: url(:/new/prefix1/btn.qss);"));
        widget_7 = new QWidget(centralWidget);
        widget_7->setObjectName(QString::fromUtf8("widget_7"));
        widget_7->setGeometry(QRect(0, 90, 931, 510));
        label_IPower_name_31 = new QLabel(widget_7);
        label_IPower_name_31->setObjectName(QString::fromUtf8("label_IPower_name_31"));
        label_IPower_name_31->setGeometry(QRect(810, 60, 61, 40));
        label_IPower_name_31->setFont(font4);
        label_env_temp_content = new QLabel(widget_7);
        label_env_temp_content->setObjectName(QString::fromUtf8("label_env_temp_content"));
        label_env_temp_content->setGeometry(QRect(260, 60, 151, 41));
        label_env_temp_content->setFont(font2);
        label_env_temp_content->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        label_IPower_name_32 = new QLabel(widget_7);
        label_IPower_name_32->setObjectName(QString::fromUtf8("label_IPower_name_32"));
        label_IPower_name_32->setGeometry(QRect(510, 60, 121, 40));
        label_IPower_name_32->setFont(font2);
        label_env_humidity_content = new QLabel(widget_7);
        label_env_humidity_content->setObjectName(QString::fromUtf8("label_env_humidity_content"));
        label_env_humidity_content->setGeometry(QRect(650, 60, 151, 41));
        label_env_humidity_content->setFont(font2);
        label_env_humidity_content->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        label_IPower_name_33 = new QLabel(widget_7);
        label_IPower_name_33->setObjectName(QString::fromUtf8("label_IPower_name_33"));
        label_IPower_name_33->setGeometry(QRect(120, 60, 121, 40));
        label_IPower_name_33->setFont(font2);
        label_IPower_name_34 = new QLabel(widget_7);
        label_IPower_name_34->setObjectName(QString::fromUtf8("label_IPower_name_34"));
        label_IPower_name_34->setGeometry(QRect(420, 60, 41, 40));
        label_IPower_name_34->setFont(font4);
        label_IPower_name_35 = new QLabel(widget_7);
        label_IPower_name_35->setObjectName(QString::fromUtf8("label_IPower_name_35"));
        label_IPower_name_35->setGeometry(QRect(810, 130, 41, 40));
        label_IPower_name_35->setFont(font4);
        label_air_temp_content = new QLabel(widget_7);
        label_air_temp_content->setObjectName(QString::fromUtf8("label_air_temp_content"));
        label_air_temp_content->setGeometry(QRect(260, 130, 151, 41));
        label_air_temp_content->setFont(font2);
        label_air_temp_content->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        label_IPower_name_36 = new QLabel(widget_7);
        label_IPower_name_36->setObjectName(QString::fromUtf8("label_IPower_name_36"));
        label_IPower_name_36->setGeometry(QRect(510, 130, 121, 40));
        label_IPower_name_36->setFont(font2);
        label_air_pressure_content = new QLabel(widget_7);
        label_air_pressure_content->setObjectName(QString::fromUtf8("label_air_pressure_content"));
        label_air_pressure_content->setGeometry(QRect(650, 130, 151, 41));
        label_air_pressure_content->setFont(font2);
        label_air_pressure_content->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        label_IPower_name_37 = new QLabel(widget_7);
        label_IPower_name_37->setObjectName(QString::fromUtf8("label_IPower_name_37"));
        label_IPower_name_37->setGeometry(QRect(120, 130, 121, 40));
        label_IPower_name_37->setFont(font2);
        label_IPower_name_38 = new QLabel(widget_7);
        label_IPower_name_38->setObjectName(QString::fromUtf8("label_IPower_name_38"));
        label_IPower_name_38->setGeometry(QRect(420, 130, 41, 40));
        label_IPower_name_38->setFont(font4);
        label_IPower_name_47 = new QLabel(widget_7);
        label_IPower_name_47->setObjectName(QString::fromUtf8("label_IPower_name_47"));
        label_IPower_name_47->setGeometry(QRect(120, 200, 121, 40));
        label_IPower_name_47->setFont(font2);
        label_IPower_name_48 = new QLabel(widget_7);
        label_IPower_name_48->setObjectName(QString::fromUtf8("label_IPower_name_48"));
        label_IPower_name_48->setGeometry(QRect(400, 175, 41, 40));
        label_IPower_name_48->setFont(font3);
        label_flow_content_1 = new QLabel(widget_7);
        label_flow_content_1->setObjectName(QString::fromUtf8("label_flow_content_1"));
        label_flow_content_1->setGeometry(QRect(260, 200, 151, 41));
        label_flow_content_1->setFont(font2);
        label_flow_content_1->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        pushButton_9 = new QPushButton(widget_7);
        pushButton_9->setObjectName(QString::fromUtf8("pushButton_9"));
        pushButton_9->setGeometry(QRect(0, 40, 81, 61));
        pushButton_9->setFont(font3);
        pushButton_9->setStyleSheet(QString::fromUtf8("border-image: url(:/new/prefix1/btn.qss);"));
        label_flow_2 = new QLabel(widget_7);
        label_flow_2->setObjectName(QString::fromUtf8("label_flow_2"));
        label_flow_2->setGeometry(QRect(420, 200, 91, 40));
        label_flow_2->setFont(font4);
        lcdNumber_clock = new QLCDNumber(centralWidget);
        lcdNumber_clock->setObjectName(QString::fromUtf8("lcdNumber_clock"));
        lcdNumber_clock->setGeometry(QRect(760, 30, 261, 31));
        lcdNumber_clock->setFrameShape(QFrame::NoFrame);
        lcdNumber_clock->setNumDigits(19);
        lcdNumber_clock->setDigitCount(19);
        lcdNumber_clock->setSegmentStyle(QLCDNumber::Flat);
        pushButton_10 = new QPushButton(centralWidget);
        pushButton_10->setObjectName(QString::fromUtf8("pushButton_10"));
        pushButton_10->setGeometry(QRect(924, 530, 101, 71));
        label_3 = new QLabel(centralWidget);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(720, 10, 30, 60));
        MainWindow->setCentralWidget(centralWidget);
        line->raise();
        label->raise();
        label_2->raise();
        pushButton_5->raise();
        pushButton->raise();
        pushButton_2->raise();
        lcdNumber_clock->raise();
        pushButton_10->raise();
        widget_6->raise();
        widget_7->raise();
        widget_5->raise();
        label_3->raise();
        widget->raise();
        widget_2->raise();

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", 0, QApplication::UnicodeUTF8));
        label->setText(QApplication::translate("MainWindow", "\350\212\202\350\203\275\345\210\206\346\236\220\344\273\252", 0, QApplication::UnicodeUTF8));
        label_2->setText(QString());
        label_IPower_name_180->setText(QApplication::translate("MainWindow", "\346\216\245\347\272\277\346\226\271\345\274\217", 0, QApplication::UnicodeUTF8));
        label_IPower_name_179->setText(QApplication::translate("MainWindow", "\344\272\222\346\204\237\345\231\250\345\217\230\346\257\224", 0, QApplication::UnicodeUTF8));
        label_IPower_name_181->setText(QApplication::translate("MainWindow", "\347\224\265\350\264\271", 0, QApplication::UnicodeUTF8));
        label_IPower_name_182->setText(QApplication::translate("MainWindow", "\351\242\235\345\256\232\345\212\237\347\216\207", 0, QApplication::UnicodeUTF8));
        label_IPower_name_183->setText(QApplication::translate("MainWindow", "\351\242\235\345\256\232\344\272\247\346\260\224\351\207\217", 0, QApplication::UnicodeUTF8));
        label_IPower_name_189->setText(QApplication::translate("MainWindow", "\347\251\272\350\275\275\346\234\200\345\244\247\347\224\265\346\265\201", 0, QApplication::UnicodeUTF8));
        label_IPower_name_190->setText(QApplication::translate("MainWindow", "\345\201\234\346\234\272\347\224\265\346\265\201", 0, QApplication::UnicodeUTF8));
        label_IPower_name_191->setText(QApplication::translate("MainWindow", "\345\212\240\350\275\275\345\216\213\345\212\233", 0, QApplication::UnicodeUTF8));
        label_IPower_name_200->setText(QApplication::translate("MainWindow", "\345\215\270\350\275\275\345\216\213\345\212\233", 0, QApplication::UnicodeUTF8));
        pushButton_12->setText(QApplication::translate("MainWindow", "\344\277\235\345\255\230", 0, QApplication::UnicodeUTF8));
        lineEdit_radio->setText(QString());
        lineEdit_charge->setText(QString());
        lineEdit_power->setText(QString());
        lineEdit_current_idle_max->setText(QString());
        lineEdit_loading_pressure->setText(QString());
        lineEdit_gas->setText(QString());
        lineEdit_current_down_max->setText(QString());
        lineEdit_unloading_pressure->setText(QString());
        label_IPower_name_184->setText(QApplication::translate("MainWindow", "\345\205\203", 0, QApplication::UnicodeUTF8));
        label_IPower_name_185->setText(QApplication::translate("MainWindow", "Kw", 0, QApplication::UnicodeUTF8));
        label_IPower_name_186->setText(QApplication::translate("MainWindow", "A", 0, QApplication::UnicodeUTF8));
        label_IPower_name_187->setText(QApplication::translate("MainWindow", "bar", 0, QApplication::UnicodeUTF8));
        label_IPower_name_188->setText(QApplication::translate("MainWindow", "bar", 0, QApplication::UnicodeUTF8));
        label_IPower_name_192->setText(QApplication::translate("MainWindow", "A", 0, QApplication::UnicodeUTF8));
        label_gas_produce_rated->setText(QApplication::translate("MainWindow", "m3/min", 0, QApplication::UnicodeUTF8));
        pushButton_16->setText(QApplication::translate("MainWindow", "\351\241\2651", 0, QApplication::UnicodeUTF8));
        pushButton_17->setText(QApplication::translate("MainWindow", "\351\241\2652", 0, QApplication::UnicodeUTF8));
        pushButton_15->setText(QApplication::translate("MainWindow", "\345\210\240\351\231\244\346\234\254\345\234\260\346\225\260\346\215\256", 0, QApplication::UnicodeUTF8));
        pushButton_18->setText(QApplication::translate("MainWindow", "\345\257\274\345\207\272\346\234\254\345\234\260\346\225\260\346\215\256", 0, QApplication::UnicodeUTF8));
        pushButton_20->setText(QApplication::translate("MainWindow", "\346\233\264\346\226\260\347\250\213\345\272\217", 0, QApplication::UnicodeUTF8));
        label_IPower_name_193->setText(QApplication::translate("MainWindow", "\345\255\230\345\202\250\346\226\271\345\274\217", 0, QApplication::UnicodeUTF8));
        label_IPower_name_81->setText(QApplication::translate("MainWindow", "\345\260\217\346\227\266", 0, QApplication::UnicodeUTF8));
        label_IPower_name_106->setText(QString());
        label_analyze_rated_flow->setText(QString());
        label_gas_produce_rated_1->setText(QApplication::translate("MainWindow", "m3/min", 0, QApplication::UnicodeUTF8));
        label_analyze_file_name->setText(QString());
        label_IPower_name_125->setText(QApplication::translate("MainWindow", "\346\226\207\344\273\266\345\220\215", 0, QApplication::UnicodeUTF8));
        label_IPower_name_126->setText(QApplication::translate("MainWindow", "\351\242\235\345\256\232\344\272\247\346\260\224\351\207\217", 0, QApplication::UnicodeUTF8));
        label_analyze_rated_power->setText(QString());
        label_IPower_name_171->setText(QApplication::translate("MainWindow", "kw", 0, QApplication::UnicodeUTF8));
        label_IPower_name_172->setText(QApplication::translate("MainWindow", "\351\242\235\345\256\232\345\212\237\347\216\207", 0, QApplication::UnicodeUTF8));
        label_analyze_standby_time->setText(QString());
        label_analyze_work_time->setText(QString());
        label_IPower_name_65->setText(QApplication::translate("MainWindow", "\345\260\217\346\227\266", 0, QApplication::UnicodeUTF8));
        label_IPower_name_66->setText(QApplication::translate("MainWindow", "\345\276\205\346\234\272\346\227\266\351\227\264", 0, QApplication::UnicodeUTF8));
        label_analyze_all_time->setText(QString());
        label_IPower_name_55->setText(QApplication::translate("MainWindow", "\345\260\217\346\227\266", 0, QApplication::UnicodeUTF8));
        label_IPower_name_52->setText(QApplication::translate("MainWindow", "\345\260\217\346\227\266", 0, QApplication::UnicodeUTF8));
        label_IPower_name_56->setText(QApplication::translate("MainWindow", "\345\267\245\344\275\234\346\227\266\351\227\264", 0, QApplication::UnicodeUTF8));
        label_IPower_name_50->setText(QApplication::translate("MainWindow", "\346\265\213\351\207\217\346\227\266\351\227\264", 0, QApplication::UnicodeUTF8));
        label_analyze_ave_vsp->setText(QString());
        label_VSP->setText(QApplication::translate("MainWindow", "Kw/(m3/min)", 0, QApplication::UnicodeUTF8));
        label_IPower_name_77->setText(QApplication::translate("MainWindow", "\345\271\263\345\235\207\346\257\224\345\212\237\347\216\207", 0, QApplication::UnicodeUTF8));
        label_acc_flow_1->setText(QApplication::translate("MainWindow", "m3", 0, QApplication::UnicodeUTF8));
        label_IPower_name_116->setText(QApplication::translate("MainWindow", "\347\224\265\350\264\271\346\200\273\351\242\235", 0, QApplication::UnicodeUTF8));
        label_analyze_start_time->setText(QString());
        label_IPower_name_113->setText(QApplication::translate("MainWindow", "\346\200\273\350\200\227\347\224\265\351\207\217", 0, QApplication::UnicodeUTF8));
        label_IPower_name_117->setText(QApplication::translate("MainWindow", "\346\260\224\344\275\223\346\210\220\346\234\254", 0, QApplication::UnicodeUTF8));
        label_cost->setText(QApplication::translate("MainWindow", "\345\205\203/m3", 0, QApplication::UnicodeUTF8));
        label_analyze_acc_flow->setText(QString());
        label_analyze_acc_power->setText(QString());
        label_IPower_name_112->setText(QApplication::translate("MainWindow", "\346\200\273\344\272\247\346\260\224\351\207\217", 0, QApplication::UnicodeUTF8));
        label_IPower_name_111->setText(QApplication::translate("MainWindow", "Kwh", 0, QApplication::UnicodeUTF8));
        label_IPower_name_115->setText(QApplication::translate("MainWindow", "\345\205\203", 0, QApplication::UnicodeUTF8));
        label_analyze_flow_cost->setText(QString());
        label_IPower_name_51->setText(QApplication::translate("MainWindow", "\345\274\200\345\247\213\346\227\266\351\227\264", 0, QApplication::UnicodeUTF8));
        label_analyze_acc_charge->setText(QString());
        label_IPower_name_108->setText(QApplication::translate("MainWindow", "\345\215\270\350\275\275\346\254\241\346\225\260", 0, QApplication::UnicodeUTF8));
        label_analyze_unload_power->setText(QString());
        label_IPower_name_105->setText(QApplication::translate("MainWindow", "\347\251\272\350\275\275\350\200\227\347\224\265", 0, QApplication::UnicodeUTF8));
        label_IPower_name_101->setText(QApplication::translate("MainWindow", "Kwh", 0, QApplication::UnicodeUTF8));
        label_IPower_name_118->setText(QApplication::translate("MainWindow", "%", 0, QApplication::UnicodeUTF8));
        label_analyze_load_charge->setText(QString());
        label_analyze_loadcnt->setText(QString());
        label_IPower_name_102->setText(QApplication::translate("MainWindow", "\345\205\203", 0, QApplication::UnicodeUTF8));
        label_IPower_name_103->setText(QApplication::translate("MainWindow", "\346\273\241\350\275\275\347\224\265\350\264\271", 0, QApplication::UnicodeUTF8));
        label_IPower_name_109->setText(QApplication::translate("MainWindow", "\345\205\203", 0, QApplication::UnicodeUTF8));
        label_IPower_name_121->setText(QApplication::translate("MainWindow", "\347\251\272\350\275\275\350\200\227\347\224\265\n"
"\345\215\240\346\257\224", 0, QApplication::UnicodeUTF8));
        label_IPower_name_99->setText(QApplication::translate("MainWindow", "\346\273\241\350\275\275\350\200\227\347\224\265", 0, QApplication::UnicodeUTF8));
        label_IPower_name_107->setText(QApplication::translate("MainWindow", "\347\251\272\350\275\275\347\224\265\350\264\271", 0, QApplication::UnicodeUTF8));
        label_analyze_load_power_radio->setText(QString());
        label_analyze_load_power->setText(QString());
        label_analyze_unload_power_radio->setText(QString());
        label_IPower_name_114->setText(QApplication::translate("MainWindow", "\345\212\240\350\275\275\346\254\241\346\225\260", 0, QApplication::UnicodeUTF8));
        label_IPower_name_110->setText(QApplication::translate("MainWindow", "Kwh", 0, QApplication::UnicodeUTF8));
        label_IPower_name_120->setText(QApplication::translate("MainWindow", "\346\273\241\350\275\275\350\200\227\347\224\265\n"
"\345\215\240\346\257\224", 0, QApplication::UnicodeUTF8));
        label_analyze_unload_charge->setText(QString());
        label_analyze_unloadcnt->setText(QString());
        label_IPower_name_119->setText(QApplication::translate("MainWindow", "%", 0, QApplication::UnicodeUTF8));
        label_IPower_name_173->setText(QApplication::translate("MainWindow", "%", 0, QApplication::UnicodeUTF8));
        label_IPower_name_80->setText(QApplication::translate("MainWindow", "\347\251\272\350\275\275\347\216\207", 0, QApplication::UnicodeUTF8));
        label_IPower_name_174->setText(QApplication::translate("MainWindow", "%", 0, QApplication::UnicodeUTF8));
        label_IPower_name_73->setText(QApplication::translate("MainWindow", "\345\260\217\346\227\266", 0, QApplication::UnicodeUTF8));
        label_IPower_name_78->setText(QApplication::translate("MainWindow", "\346\273\241\350\275\275\346\227\266\351\227\264", 0, QApplication::UnicodeUTF8));
        label_analyze_unload_radio->setText(QString());
        label_IPower_name_75->setText(QApplication::translate("MainWindow", "\345\260\217\346\227\266", 0, QApplication::UnicodeUTF8));
        label_IPower_name_84->setText(QApplication::translate("MainWindow", "\346\273\241\350\275\275\347\216\207", 0, QApplication::UnicodeUTF8));
        label_analyze_loadtime->setText(QString());
        label_analyze_unloadtime->setText(QString());
        label_IPower_name_74->setText(QApplication::translate("MainWindow", "\347\251\272\350\275\275\346\227\266\351\227\264", 0, QApplication::UnicodeUTF8));
        label_analyze_load_radio->setText(QString());
        pushButton_11->setText(QApplication::translate("MainWindow", "\351\241\2651", 0, QApplication::UnicodeUTF8));
        pushButton_13->setText(QApplication::translate("MainWindow", "\351\241\2652", 0, QApplication::UnicodeUTF8));
        pushButton_14->setText(QApplication::translate("MainWindow", "\351\200\211\346\213\251", 0, QApplication::UnicodeUTF8));
        pushButton_19->setText(QApplication::translate("MainWindow", "\345\257\274\345\207\272", 0, QApplication::UnicodeUTF8));
        pushButton_5->setText(QApplication::translate("MainWindow", "\345\210\206\346\236\220", 0, QApplication::UnicodeUTF8));
        pushButton->setText(QApplication::translate("MainWindow", "\350\256\276\347\275\256", 0, QApplication::UnicodeUTF8));
        pushButton_2->setText(QApplication::translate("MainWindow", "\346\237\245\347\234\213", 0, QApplication::UnicodeUTF8));
        label_IPower_name->setText(QApplication::translate("MainWindow", "\347\236\254\346\227\266\345\212\237\347\216\207", 0, QApplication::UnicodeUTF8));
        label_Power_name->setText(QApplication::translate("MainWindow", "\347\224\250\347\224\265\351\207\217", 0, QApplication::UnicodeUTF8));
        label_power_content->setText(QString());
        label_IPower_name_3->setText(QApplication::translate("MainWindow", "\347\264\257\350\256\241\346\265\201\351\207\217", 0, QApplication::UnicodeUTF8));
        label_IPower_content->setText(QString());
        label_flow_content->setText(QString());
        label_IPower_name_2->setText(QApplication::translate("MainWindow", "\347\236\254\346\227\266\346\265\201\351\207\217", 0, QApplication::UnicodeUTF8));
        label_IFlow_content->setText(QString());
        label_IPower_name_13->setText(QApplication::translate("MainWindow", "\345\274\200\345\247\213\346\227\266\351\227\264", 0, QApplication::UnicodeUTF8));
        label_start_time_content->setText(QString());
        label_IPower_name_14->setText(QApplication::translate("MainWindow", "\346\214\201\347\273\255\346\227\266\351\227\264", 0, QApplication::UnicodeUTF8));
        label_end_time_content->setText(QString());
        pushButton_6->setText(QApplication::translate("MainWindow", "\347\224\265\350\241\250", 0, QApplication::UnicodeUTF8));
        pushButton_7->setText(QApplication::translate("MainWindow", "\344\274\240\346\204\237\345\231\250", 0, QApplication::UnicodeUTF8));
        label_IPower_name_46->setText(QApplication::translate("MainWindow", "\345\212\240\350\275\275\347\216\207", 0, QApplication::UnicodeUTF8));
        label_loding_rate_content->setText(QString());
        label_Power_name_3->setText(QApplication::translate("MainWindow", "\346\257\224\345\212\237\347\216\207", 0, QApplication::UnicodeUTF8));
        label_power_radio_content->setText(QString());
        label_IPower_name_22->setText(QApplication::translate("MainWindow", "Kw", 0, QApplication::UnicodeUTF8));
        label_IPower_name_54->setText(QApplication::translate("MainWindow", "Kwh", 0, QApplication::UnicodeUTF8));
        label_VSP_1->setText(QApplication::translate("MainWindow", "Kw", 0, QApplication::UnicodeUTF8));
        label_flow_unit->setText(QApplication::translate("MainWindow", "m3/min", 0, QApplication::UnicodeUTF8));
        label_acc_flow_unit->setText(QApplication::translate("MainWindow", "unit", 0, QApplication::UnicodeUTF8));
        label_flow_unit_3->setText(QApplication::translate("MainWindow", "%", 0, QApplication::UnicodeUTF8));
        pushButton_3->setText(QApplication::translate("MainWindow", "\345\274\200\345\247\213", 0, QApplication::UnicodeUTF8));
        pushButton_4->setText(QApplication::translate("MainWindow", "\347\273\223\346\235\237", 0, QApplication::UnicodeUTF8));
        pushButton_21->setText(QApplication::translate("MainWindow", "\346\210\252\345\233\276", 0, QApplication::UnicodeUTF8));
        label_IPower_name_5->setText(QApplication::translate("MainWindow", "A\347\233\270", 0, QApplication::UnicodeUTF8));
        label_voltage_a_content->setText(QString());
        label_IPower_name_6->setText(QApplication::translate("MainWindow", "B\347\233\270", 0, QApplication::UnicodeUTF8));
        label_voltage_b_content->setText(QString());
        label_IPower_name_7->setText(QApplication::translate("MainWindow", "C\347\233\270", 0, QApplication::UnicodeUTF8));
        label_voltage_c_content->setText(QString());
        label_current_c_content->setText(QString());
        label_current_b_content->setText(QString());
        label_current_a_content->setText(QString());
        label_IPower_name_8->setText(QApplication::translate("MainWindow", "\347\224\265\345\216\213", 0, QApplication::UnicodeUTF8));
        label_IPower_name_12->setText(QApplication::translate("MainWindow", "\347\224\265\346\265\201", 0, QApplication::UnicodeUTF8));
        label_IPower_name_15->setText(QApplication::translate("MainWindow", "V", 0, QApplication::UnicodeUTF8));
        label_IPower_name_16->setText(QApplication::translate("MainWindow", "V", 0, QApplication::UnicodeUTF8));
        label_IPower_name_17->setText(QApplication::translate("MainWindow", "V", 0, QApplication::UnicodeUTF8));
        label_IPower_name_18->setText(QApplication::translate("MainWindow", "A", 0, QApplication::UnicodeUTF8));
        label_IPower_name_19->setText(QApplication::translate("MainWindow", "A", 0, QApplication::UnicodeUTF8));
        label_IPower_name_20->setText(QApplication::translate("MainWindow", "A", 0, QApplication::UnicodeUTF8));
        label_IPower_name_21->setText(QApplication::translate("MainWindow", "\351\242\221\347\216\207", 0, QApplication::UnicodeUTF8));
        label_frequency_content->setText(QString());
        label_IPower_name_23->setText(QApplication::translate("MainWindow", "\345\212\237\347\216\207\345\233\240\347\264\240", 0, QApplication::UnicodeUTF8));
        label_power_factor_content->setText(QString());
        label_IPower_name_25->setText(QApplication::translate("MainWindow", "\346\234\211\345\212\237\345\212\237\347\216\207", 0, QApplication::UnicodeUTF8));
        label_active_power_content->setText(QString());
        label_IPower_name_26->setText(QApplication::translate("MainWindow", "Kw", 0, QApplication::UnicodeUTF8));
        label_IPower_name_27->setText(QApplication::translate("MainWindow", "\346\227\240\345\212\237\345\212\237\347\216\207", 0, QApplication::UnicodeUTF8));
        label_reactive_power_content->setText(QString());
        label_IPower_name_28->setText(QApplication::translate("MainWindow", "Kavr", 0, QApplication::UnicodeUTF8));
        label_IPower_name_29->setText(QApplication::translate("MainWindow", "KVA", 0, QApplication::UnicodeUTF8));
        label_IPower_name_30->setText(QApplication::translate("MainWindow", "\350\247\206\345\234\250\345\212\237\347\216\207", 0, QApplication::UnicodeUTF8));
        label_apparent_power_content->setText(QString());
        pushButton_8->setText(QApplication::translate("MainWindow", "\350\277\224\345\233\236", 0, QApplication::UnicodeUTF8));
        label_IPower_name_31->setText(QApplication::translate("MainWindow", "%rh", 0, QApplication::UnicodeUTF8));
        label_env_temp_content->setText(QString());
        label_IPower_name_32->setText(QApplication::translate("MainWindow", "\347\216\257\345\242\203\346\271\277\345\272\246", 0, QApplication::UnicodeUTF8));
        label_env_humidity_content->setText(QString());
        label_IPower_name_33->setText(QApplication::translate("MainWindow", "\347\216\257\345\242\203\346\270\251\345\272\246", 0, QApplication::UnicodeUTF8));
        label_IPower_name_34->setText(QApplication::translate("MainWindow", "\342\204\203", 0, QApplication::UnicodeUTF8));
        label_IPower_name_35->setText(QApplication::translate("MainWindow", "bar", 0, QApplication::UnicodeUTF8));
        label_air_temp_content->setText(QString());
        label_IPower_name_36->setText(QApplication::translate("MainWindow", "\346\216\222\346\260\224\345\216\213\345\212\233", 0, QApplication::UnicodeUTF8));
        label_air_pressure_content->setText(QString());
        label_IPower_name_37->setText(QApplication::translate("MainWindow", "\346\216\222\346\260\224\346\270\251\345\272\246", 0, QApplication::UnicodeUTF8));
        label_IPower_name_38->setText(QApplication::translate("MainWindow", "\342\204\203", 0, QApplication::UnicodeUTF8));
        label_IPower_name_47->setText(QApplication::translate("MainWindow", "\346\265\201\351\207\217", 0, QApplication::UnicodeUTF8));
        label_IPower_name_48->setText(QString());
        label_flow_content_1->setText(QString());
        pushButton_9->setText(QApplication::translate("MainWindow", "\350\277\224\345\233\236", 0, QApplication::UnicodeUTF8));
        label_flow_2->setText(QApplication::translate("MainWindow", "m3/min", 0, QApplication::UnicodeUTF8));
        pushButton_10->setText(QApplication::translate("MainWindow", "PushButton", 0, QApplication::UnicodeUTF8));
        label_3->setText(QString());
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
