/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 4.8.6
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QComboBox>
#include <QtGui/QFrame>
#include <QtGui/QHeaderView>
#include <QtGui/QLCDNumber>
#include <QtGui/QLabel>
#include <QtGui/QLineEdit>
#include <QtGui/QMainWindow>
#include <QtGui/QPushButton>
#include <QtGui/QWidget>
#include "qwt_dial.h"

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralWidget;
    QFrame *line;
    QLabel *label;
    QLabel *label_2;
    QPushButton *pushButton_4;
    QWidget *widget;
    QLabel *label_IPower_name_180;
    QLabel *label_IPower_name_179;
    QLabel *label_IPower_name_181;
    QLabel *label_IPower_name_182;
    QLabel *label_IPower_name_183;
    QLabel *label_IPower_name_189;
    QLabel *label_IPower_name_190;
    QLabel *label_IPower_name_191;
    QLabel *label_IPower_name_200;
    QPushButton *pushButton_12;
    QLineEdit *lineEdit_radio;
    QLineEdit *lineEdit_charge;
    QLineEdit *lineEdit_power;
    QLineEdit *lineEdit_current_idle_max;
    QLineEdit *lineEdit_loading_pressure;
    QLineEdit *lineEdit_gas;
    QLineEdit *lineEdit_current_down_max;
    QLineEdit *lineEdit_unloading_pressure;
    QComboBox *comboBox_store_type;
    QWidget *widget_5;
    QLabel *label_IPower_content_37;
    QLabel *label_IPower_name_50;
    QLabel *label_IPower_name_52;
    QLabel *label_IPower_content_40;
    QLabel *label_IPower_name_55;
    QLabel *label_IPower_name_56;
    QLabel *label_IPower_content_45;
    QLabel *label_IPower_name_65;
    QLabel *label_IPower_name_66;
    QLabel *label_IPower_content_49;
    QLabel *label_IPower_name_73;
    QLabel *label_IPower_name_74;
    QLabel *label_IPower_name_75;
    QLabel *label_IPower_content_50;
    QLabel *label_IPower_content_51;
    QLabel *label_IPower_name_76;
    QLabel *label_IPower_name_77;
    QLabel *label_IPower_name_78;
    QLabel *label_IPower_content_52;
    QLabel *label_IPower_name_79;
    QLabel *label_IPower_name_80;
    QLabel *label_IPower_name_81;
    QLabel *label_IPower_content_53;
    QLabel *label_IPower_name_84;
    QFrame *line_9;
    QLabel *label_IPower_name_99;
    QLabel *label_IPower_content_62;
    QLabel *label_IPower_content_63;
    QLabel *label_IPower_name_100;
    QLabel *label_IPower_content_64;
    QLabel *label_IPower_name_101;
    QLabel *label_IPower_name_102;
    QLabel *label_IPower_name_103;
    QLabel *label_IPower_name_104;
    QLabel *label_IPower_content_65;
    QLabel *label_IPower_content_66;
    QLabel *label_IPower_name_105;
    QLabel *label_IPower_name_106;
    QLabel *label_IPower_name_107;
    QLabel *label_IPower_content_67;
    QLabel *label_IPower_name_108;
    QLabel *label_IPower_content_68;
    QLabel *label_IPower_name_109;
    QLabel *label_IPower_name_110;
    QLabel *label_IPower_name_111;
    QLabel *label_IPower_name_112;
    QLabel *label_IPower_name_114;
    QLabel *label_IPower_content_69;
    QLabel *label_IPower_name_113;
    QLabel *label_IPower_content_70;
    QLabel *label_IPower_name_115;
    QLabel *label_IPower_name_116;
    QLabel *label_IPower_name_117;
    QLabel *label_IPower_content_71;
    QLabel *label_IPower_name_118;
    QLabel *label_IPower_name_119;
    QLabel *label_IPower_content_72;
    QLabel *label_IPower_content_73;
    QLabel *label_IPower_name_120;
    QLabel *label_IPower_name_121;
    QLabel *label_IPower_name_122;
    QFrame *line_11;
    QLabel *label_IPower_content_74;
    QLabel *label_IPower_name_123;
    QLabel *label_IPower_content_75;
    QLabel *label_IPower_name_124;
    QLabel *label_IPower_name_125;
    QLabel *label_IPower_name_126;
    QLabel *label_IPower_content_98;
    QLabel *label_IPower_name_171;
    QLabel *label_IPower_name_172;
    QLabel *label_IPower_name_173;
    QLabel *label_IPower_name_174;
    QPushButton *pushButton_5;
    QPushButton *pushButton;
    QPushButton *pushButton_2;
    QPushButton *pushButton_3;
    QWidget *widget_2;
    QLabel *label_IPower_name;
    QLabel *label_Power_name;
    QLabel *label_power_save_a_content;
    QwtDial *Dial;
    QLabel *label_power_save_b_content;
    QLabel *label_IPower_name_4;
    QLabel *label_power_saverate_a_content;
    QwtDial *Dial_2;
    QLabel *label_power_content;
    QFrame *line_2;
    QLabel *label_IPower_name_3;
    QLabel *label_IPower_content;
    QFrame *line_3;
    QLabel *label_flow_content;
    QLabel *label_IPower_name_9;
    QLabel *label_power_saverate_b_content;
    QLabel *label_IPower_name_2;
    QLabel *label_IFlow_content;
    QLabel *label_IPower_name_10;
    QLabel *label_IPower_name_11;
    QFrame *line_4;
    QLabel *label_IPower_name_13;
    QLabel *label_start_time_content;
    QLabel *label_IPower_name_14;
    QLabel *label_end_time_content;
    QPushButton *pushButton_6;
    QPushButton *pushButton_7;
    QLabel *label_IPower_name_46;
    QLabel *label_loding_rate_content;
    QLabel *label_Power_name_3;
    QLabel *label_power_radio_content;
    QWidget *widget_6;
    QLabel *label_IPower_name_5;
    QLabel *label_voltage_a_content;
    QLabel *label_IPower_name_6;
    QLabel *label_voltage_b_content;
    QLabel *label_IPower_name_7;
    QLabel *label_voltage_c_content;
    QLabel *label_current_c_content;
    QLabel *label_current_b_content;
    QLabel *label_current_a_content;
    QLabel *label_IPower_name_8;
    QLabel *label_IPower_name_12;
    QLabel *label_IPower_name_15;
    QLabel *label_IPower_name_16;
    QLabel *label_IPower_name_17;
    QLabel *label_IPower_name_18;
    QLabel *label_IPower_name_19;
    QLabel *label_IPower_name_20;
    QLabel *label_IPower_name_21;
    QLabel *label_frequency_content;
    QLabel *label_IPower_name_23;
    QLabel *label_power_factor_content;
    QLabel *label_IPower_name_25;
    QLabel *label_active_power_content;
    QLabel *label_IPower_name_26;
    QLabel *label_IPower_name_27;
    QLabel *label_reactive_power_content;
    QLabel *label_IPower_name_28;
    QLabel *label_IPower_name_29;
    QLabel *label_IPower_name_30;
    QLabel *label_apparent_power_content;
    QFrame *line_5;
    QPushButton *pushButton_8;
    QWidget *widget_7;
    QLabel *label_IPower_name_31;
    QLabel *label_env_temp_content;
    QLabel *label_IPower_name_32;
    QLabel *label_env_humidity_content;
    QLabel *label_IPower_name_33;
    QLabel *label_IPower_name_34;
    QLabel *label_IPower_name_35;
    QLabel *label_air_temp_content;
    QLabel *label_IPower_name_36;
    QLabel *label_air_pressure_content;
    QLabel *label_IPower_name_37;
    QLabel *label_IPower_name_38;
    QLabel *label_IPower_name_47;
    QLabel *label_IPower_name_48;
    QLabel *label_flow_content_1;
    QPushButton *pushButton_9;
    QLCDNumber *lcdNumber_clock;
    QPushButton *pushButton_10;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->resize(1024, 601);
        QFont font;
        font.setFamily(QString::fromUtf8("ADMUI3Lg"));
        MainWindow->setFont(font);
        MainWindow->setStyleSheet(QString::fromUtf8("background-color: rgb(96, 125, 139);"));
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QString::fromUtf8("centralWidget"));
        line = new QFrame(centralWidget);
        line->setObjectName(QString::fromUtf8("line"));
        line->setGeometry(QRect(0, 80, 1024, 3));
        line->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        line->setFrameShape(QFrame::HLine);
        line->setFrameShadow(QFrame::Sunken);
        label = new QLabel(centralWidget);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(250, 20, 161, 30));
        QFont font1;
        font1.setFamily(QString::fromUtf8("\345\276\256\350\275\257\351\233\205\351\273\221"));
        font1.setPointSize(22);
        font1.setBold(false);
        font1.setWeight(50);
        label->setFont(font1);
        label_2 = new QLabel(centralWidget);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(10, 20, 200, 40));
        pushButton_4 = new QPushButton(centralWidget);
        pushButton_4->setObjectName(QString::fromUtf8("pushButton_4"));
        pushButton_4->setGeometry(QRect(930, 380, 100, 70));
        QFont font2;
        font2.setFamily(QString::fromUtf8("\345\276\256\350\275\257\351\233\205\351\273\221"));
        font2.setPointSize(14);
        pushButton_4->setFont(font2);
        widget = new QWidget(centralWidget);
        widget->setObjectName(QString::fromUtf8("widget"));
        widget->setGeometry(QRect(0, 90, 900, 510));
        label_IPower_name_180 = new QLabel(widget);
        label_IPower_name_180->setObjectName(QString::fromUtf8("label_IPower_name_180"));
        label_IPower_name_180->setGeometry(QRect(520, 40, 101, 40));
        QFont font3;
        font3.setFamily(QString::fromUtf8("\345\276\256\350\275\257\351\233\205\351\273\221"));
        font3.setPointSize(18);
        label_IPower_name_180->setFont(font3);
        label_IPower_name_179 = new QLabel(widget);
        label_IPower_name_179->setObjectName(QString::fromUtf8("label_IPower_name_179"));
        label_IPower_name_179->setGeometry(QRect(170, 40, 121, 40));
        label_IPower_name_179->setFont(font3);
        label_IPower_name_181 = new QLabel(widget);
        label_IPower_name_181->setObjectName(QString::fromUtf8("label_IPower_name_181"));
        label_IPower_name_181->setGeometry(QRect(240, 100, 51, 40));
        label_IPower_name_181->setFont(font3);
        label_IPower_name_182 = new QLabel(widget);
        label_IPower_name_182->setObjectName(QString::fromUtf8("label_IPower_name_182"));
        label_IPower_name_182->setGeometry(QRect(190, 160, 101, 40));
        label_IPower_name_182->setFont(font3);
        label_IPower_name_183 = new QLabel(widget);
        label_IPower_name_183->setObjectName(QString::fromUtf8("label_IPower_name_183"));
        label_IPower_name_183->setGeometry(QRect(500, 160, 121, 40));
        label_IPower_name_183->setFont(font3);
        label_IPower_name_189 = new QLabel(widget);
        label_IPower_name_189->setObjectName(QString::fromUtf8("label_IPower_name_189"));
        label_IPower_name_189->setGeometry(QRect(140, 220, 151, 40));
        label_IPower_name_189->setFont(font3);
        label_IPower_name_190 = new QLabel(widget);
        label_IPower_name_190->setObjectName(QString::fromUtf8("label_IPower_name_190"));
        label_IPower_name_190->setGeometry(QRect(520, 220, 101, 40));
        label_IPower_name_190->setFont(font3);
        label_IPower_name_191 = new QLabel(widget);
        label_IPower_name_191->setObjectName(QString::fromUtf8("label_IPower_name_191"));
        label_IPower_name_191->setGeometry(QRect(190, 280, 101, 40));
        label_IPower_name_191->setFont(font3);
        label_IPower_name_200 = new QLabel(widget);
        label_IPower_name_200->setObjectName(QString::fromUtf8("label_IPower_name_200"));
        label_IPower_name_200->setGeometry(QRect(520, 280, 111, 40));
        label_IPower_name_200->setFont(font3);
        pushButton_12 = new QPushButton(widget);
        pushButton_12->setObjectName(QString::fromUtf8("pushButton_12"));
        pushButton_12->setGeometry(QRect(0, 80, 81, 51));
        pushButton_12->setFont(font2);
        pushButton_12->setStyleSheet(QString::fromUtf8("border-image: url(:/new/prefix1/btn.qss);"));
        lineEdit_radio = new QLineEdit(widget);
        lineEdit_radio->setObjectName(QString::fromUtf8("lineEdit_radio"));
        lineEdit_radio->setGeometry(QRect(300, 40, 120, 35));
        lineEdit_radio->setFont(font3);
        lineEdit_radio->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lineEdit_radio->setMaxLength(10);
        lineEdit_charge = new QLineEdit(widget);
        lineEdit_charge->setObjectName(QString::fromUtf8("lineEdit_charge"));
        lineEdit_charge->setGeometry(QRect(300, 100, 120, 35));
        lineEdit_charge->setFont(font3);
        lineEdit_charge->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lineEdit_charge->setMaxLength(10);
        lineEdit_power = new QLineEdit(widget);
        lineEdit_power->setObjectName(QString::fromUtf8("lineEdit_power"));
        lineEdit_power->setGeometry(QRect(300, 160, 120, 35));
        lineEdit_power->setFont(font3);
        lineEdit_power->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lineEdit_power->setMaxLength(10);
        lineEdit_current_idle_max = new QLineEdit(widget);
        lineEdit_current_idle_max->setObjectName(QString::fromUtf8("lineEdit_current_idle_max"));
        lineEdit_current_idle_max->setGeometry(QRect(300, 220, 120, 35));
        lineEdit_current_idle_max->setFont(font3);
        lineEdit_current_idle_max->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lineEdit_current_idle_max->setMaxLength(10);
        lineEdit_loading_pressure = new QLineEdit(widget);
        lineEdit_loading_pressure->setObjectName(QString::fromUtf8("lineEdit_loading_pressure"));
        lineEdit_loading_pressure->setGeometry(QRect(300, 280, 120, 35));
        lineEdit_loading_pressure->setFont(font3);
        lineEdit_loading_pressure->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lineEdit_loading_pressure->setMaxLength(10);
        lineEdit_gas = new QLineEdit(widget);
        lineEdit_gas->setObjectName(QString::fromUtf8("lineEdit_gas"));
        lineEdit_gas->setGeometry(QRect(640, 160, 120, 35));
        lineEdit_gas->setFont(font3);
        lineEdit_gas->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lineEdit_gas->setMaxLength(10);
        lineEdit_current_down_max = new QLineEdit(widget);
        lineEdit_current_down_max->setObjectName(QString::fromUtf8("lineEdit_current_down_max"));
        lineEdit_current_down_max->setGeometry(QRect(640, 220, 120, 35));
        lineEdit_current_down_max->setFont(font3);
        lineEdit_current_down_max->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lineEdit_current_down_max->setMaxLength(10);
        lineEdit_unloading_pressure = new QLineEdit(widget);
        lineEdit_unloading_pressure->setObjectName(QString::fromUtf8("lineEdit_unloading_pressure"));
        lineEdit_unloading_pressure->setGeometry(QRect(640, 280, 120, 35));
        lineEdit_unloading_pressure->setFont(font3);
        lineEdit_unloading_pressure->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lineEdit_unloading_pressure->setMaxLength(10);
        comboBox_store_type = new QComboBox(widget);
        comboBox_store_type->setObjectName(QString::fromUtf8("comboBox_store_type"));
        comboBox_store_type->setGeometry(QRect(640, 40, 111, 40));
        comboBox_store_type->setFont(font3);
        comboBox_store_type->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 248, 249);"));
        comboBox_store_type->setMaxCount(3);
        label_IPower_name_180->raise();
        label_IPower_name_179->raise();
        label_IPower_name_181->raise();
        label_IPower_name_182->raise();
        label_IPower_name_183->raise();
        label_IPower_name_189->raise();
        label_IPower_name_190->raise();
        label_IPower_name_191->raise();
        label_IPower_name_200->raise();
        pushButton_12->raise();
        lineEdit_radio->raise();
        lineEdit_charge->raise();
        lineEdit_power->raise();
        lineEdit_current_idle_max->raise();
        lineEdit_loading_pressure->raise();
        lineEdit_gas->raise();
        lineEdit_current_down_max->raise();
        lineEdit_unloading_pressure->raise();
        comboBox_store_type->raise();
        widget_5 = new QWidget(centralWidget);
        widget_5->setObjectName(QString::fromUtf8("widget_5"));
        widget_5->setGeometry(QRect(0, 90, 900, 500));
        label_IPower_content_37 = new QLabel(widget_5);
        label_IPower_content_37->setObjectName(QString::fromUtf8("label_IPower_content_37"));
        label_IPower_content_37->setGeometry(QRect(110, 115, 121, 30));
        label_IPower_content_37->setFont(font2);
        label_IPower_content_37->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        label_IPower_name_50 = new QLabel(widget_5);
        label_IPower_name_50->setObjectName(QString::fromUtf8("label_IPower_name_50"));
        label_IPower_name_50->setGeometry(QRect(20, 110, 81, 40));
        label_IPower_name_50->setFont(font2);
        label_IPower_name_52 = new QLabel(widget_5);
        label_IPower_name_52->setObjectName(QString::fromUtf8("label_IPower_name_52"));
        label_IPower_name_52->setGeometry(QRect(240, 110, 81, 40));
        label_IPower_name_52->setFont(font2);
        label_IPower_content_40 = new QLabel(widget_5);
        label_IPower_content_40->setObjectName(QString::fromUtf8("label_IPower_content_40"));
        label_IPower_content_40->setGeometry(QRect(420, 115, 121, 30));
        label_IPower_content_40->setFont(font2);
        label_IPower_content_40->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        label_IPower_name_55 = new QLabel(widget_5);
        label_IPower_name_55->setObjectName(QString::fromUtf8("label_IPower_name_55"));
        label_IPower_name_55->setGeometry(QRect(550, 110, 81, 40));
        label_IPower_name_55->setFont(font2);
        label_IPower_name_56 = new QLabel(widget_5);
        label_IPower_name_56->setObjectName(QString::fromUtf8("label_IPower_name_56"));
        label_IPower_name_56->setGeometry(QRect(330, 110, 81, 40));
        label_IPower_name_56->setFont(font2);
        label_IPower_content_45 = new QLabel(widget_5);
        label_IPower_content_45->setObjectName(QString::fromUtf8("label_IPower_content_45"));
        label_IPower_content_45->setGeometry(QRect(730, 115, 121, 30));
        label_IPower_content_45->setFont(font2);
        label_IPower_content_45->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        label_IPower_name_65 = new QLabel(widget_5);
        label_IPower_name_65->setObjectName(QString::fromUtf8("label_IPower_name_65"));
        label_IPower_name_65->setGeometry(QRect(860, 110, 81, 40));
        label_IPower_name_65->setFont(font2);
        label_IPower_name_66 = new QLabel(widget_5);
        label_IPower_name_66->setObjectName(QString::fromUtf8("label_IPower_name_66"));
        label_IPower_name_66->setGeometry(QRect(640, 110, 81, 40));
        label_IPower_name_66->setFont(font2);
        label_IPower_content_49 = new QLabel(widget_5);
        label_IPower_content_49->setObjectName(QString::fromUtf8("label_IPower_content_49"));
        label_IPower_content_49->setGeometry(QRect(420, 165, 121, 30));
        label_IPower_content_49->setFont(font2);
        label_IPower_content_49->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        label_IPower_name_73 = new QLabel(widget_5);
        label_IPower_name_73->setObjectName(QString::fromUtf8("label_IPower_name_73"));
        label_IPower_name_73->setGeometry(QRect(550, 160, 81, 40));
        label_IPower_name_73->setFont(font2);
        label_IPower_name_74 = new QLabel(widget_5);
        label_IPower_name_74->setObjectName(QString::fromUtf8("label_IPower_name_74"));
        label_IPower_name_74->setGeometry(QRect(640, 160, 81, 40));
        label_IPower_name_74->setFont(font2);
        label_IPower_name_75 = new QLabel(widget_5);
        label_IPower_name_75->setObjectName(QString::fromUtf8("label_IPower_name_75"));
        label_IPower_name_75->setGeometry(QRect(860, 160, 81, 40));
        label_IPower_name_75->setFont(font2);
        label_IPower_content_50 = new QLabel(widget_5);
        label_IPower_content_50->setObjectName(QString::fromUtf8("label_IPower_content_50"));
        label_IPower_content_50->setGeometry(QRect(730, 165, 121, 30));
        label_IPower_content_50->setFont(font2);
        label_IPower_content_50->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        label_IPower_content_51 = new QLabel(widget_5);
        label_IPower_content_51->setObjectName(QString::fromUtf8("label_IPower_content_51"));
        label_IPower_content_51->setGeometry(QRect(110, 165, 121, 30));
        label_IPower_content_51->setFont(font2);
        label_IPower_content_51->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        label_IPower_name_76 = new QLabel(widget_5);
        label_IPower_name_76->setObjectName(QString::fromUtf8("label_IPower_name_76"));
        label_IPower_name_76->setGeometry(QRect(240, 160, 81, 40));
        label_IPower_name_76->setFont(font2);
        label_IPower_name_77 = new QLabel(widget_5);
        label_IPower_name_77->setObjectName(QString::fromUtf8("label_IPower_name_77"));
        label_IPower_name_77->setGeometry(QRect(10, 160, 101, 40));
        label_IPower_name_77->setFont(font2);
        label_IPower_name_78 = new QLabel(widget_5);
        label_IPower_name_78->setObjectName(QString::fromUtf8("label_IPower_name_78"));
        label_IPower_name_78->setGeometry(QRect(330, 160, 81, 40));
        label_IPower_name_78->setFont(font2);
        label_IPower_content_52 = new QLabel(widget_5);
        label_IPower_content_52->setObjectName(QString::fromUtf8("label_IPower_content_52"));
        label_IPower_content_52->setGeometry(QRect(420, 215, 121, 30));
        label_IPower_content_52->setFont(font2);
        label_IPower_content_52->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        label_IPower_name_79 = new QLabel(widget_5);
        label_IPower_name_79->setObjectName(QString::fromUtf8("label_IPower_name_79"));
        label_IPower_name_79->setGeometry(QRect(550, 210, 81, 40));
        label_IPower_name_79->setFont(font2);
        label_IPower_name_80 = new QLabel(widget_5);
        label_IPower_name_80->setObjectName(QString::fromUtf8("label_IPower_name_80"));
        label_IPower_name_80->setGeometry(QRect(640, 210, 81, 40));
        label_IPower_name_80->setFont(font2);
        label_IPower_name_81 = new QLabel(widget_5);
        label_IPower_name_81->setObjectName(QString::fromUtf8("label_IPower_name_81"));
        label_IPower_name_81->setGeometry(QRect(860, 210, 81, 40));
        label_IPower_name_81->setFont(font2);
        label_IPower_content_53 = new QLabel(widget_5);
        label_IPower_content_53->setObjectName(QString::fromUtf8("label_IPower_content_53"));
        label_IPower_content_53->setGeometry(QRect(730, 215, 121, 30));
        label_IPower_content_53->setFont(font2);
        label_IPower_content_53->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        label_IPower_name_84 = new QLabel(widget_5);
        label_IPower_name_84->setObjectName(QString::fromUtf8("label_IPower_name_84"));
        label_IPower_name_84->setGeometry(QRect(330, 210, 81, 40));
        label_IPower_name_84->setFont(font2);
        line_9 = new QFrame(widget_5);
        line_9->setObjectName(QString::fromUtf8("line_9"));
        line_9->setGeometry(QRect(0, 260, 921, 16));
        line_9->setFrameShape(QFrame::HLine);
        line_9->setFrameShadow(QFrame::Sunken);
        label_IPower_name_99 = new QLabel(widget_5);
        label_IPower_name_99->setObjectName(QString::fromUtf8("label_IPower_name_99"));
        label_IPower_name_99->setGeometry(QRect(330, 335, 81, 40));
        label_IPower_name_99->setFont(font2);
        label_IPower_content_62 = new QLabel(widget_5);
        label_IPower_content_62->setObjectName(QString::fromUtf8("label_IPower_content_62"));
        label_IPower_content_62->setGeometry(QRect(110, 290, 121, 30));
        label_IPower_content_62->setFont(font2);
        label_IPower_content_62->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        label_IPower_content_63 = new QLabel(widget_5);
        label_IPower_content_63->setObjectName(QString::fromUtf8("label_IPower_content_63"));
        label_IPower_content_63->setGeometry(QRect(420, 290, 121, 30));
        label_IPower_content_63->setFont(font2);
        label_IPower_content_63->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        label_IPower_name_100 = new QLabel(widget_5);
        label_IPower_name_100->setObjectName(QString::fromUtf8("label_IPower_name_100"));
        label_IPower_name_100->setGeometry(QRect(240, 285, 81, 40));
        label_IPower_name_100->setFont(font2);
        label_IPower_content_64 = new QLabel(widget_5);
        label_IPower_content_64->setObjectName(QString::fromUtf8("label_IPower_content_64"));
        label_IPower_content_64->setGeometry(QRect(420, 340, 121, 30));
        label_IPower_content_64->setFont(font2);
        label_IPower_content_64->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        label_IPower_name_101 = new QLabel(widget_5);
        label_IPower_name_101->setObjectName(QString::fromUtf8("label_IPower_name_101"));
        label_IPower_name_101->setGeometry(QRect(550, 335, 81, 40));
        label_IPower_name_101->setFont(font2);
        label_IPower_name_102 = new QLabel(widget_5);
        label_IPower_name_102->setObjectName(QString::fromUtf8("label_IPower_name_102"));
        label_IPower_name_102->setGeometry(QRect(550, 385, 81, 40));
        label_IPower_name_102->setFont(font2);
        label_IPower_name_103 = new QLabel(widget_5);
        label_IPower_name_103->setObjectName(QString::fromUtf8("label_IPower_name_103"));
        label_IPower_name_103->setGeometry(QRect(330, 385, 81, 40));
        label_IPower_name_103->setFont(font2);
        label_IPower_name_104 = new QLabel(widget_5);
        label_IPower_name_104->setObjectName(QString::fromUtf8("label_IPower_name_104"));
        label_IPower_name_104->setGeometry(QRect(550, 205, 81, 40));
        label_IPower_name_104->setFont(font2);
        label_IPower_content_65 = new QLabel(widget_5);
        label_IPower_content_65->setObjectName(QString::fromUtf8("label_IPower_content_65"));
        label_IPower_content_65->setGeometry(QRect(420, 390, 121, 30));
        label_IPower_content_65->setFont(font2);
        label_IPower_content_65->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        label_IPower_content_66 = new QLabel(widget_5);
        label_IPower_content_66->setObjectName(QString::fromUtf8("label_IPower_content_66"));
        label_IPower_content_66->setGeometry(QRect(110, 340, 121, 30));
        label_IPower_content_66->setFont(font2);
        label_IPower_content_66->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        label_IPower_name_105 = new QLabel(widget_5);
        label_IPower_name_105->setObjectName(QString::fromUtf8("label_IPower_name_105"));
        label_IPower_name_105->setGeometry(QRect(640, 335, 81, 40));
        label_IPower_name_105->setFont(font2);
        label_IPower_name_106 = new QLabel(widget_5);
        label_IPower_name_106->setObjectName(QString::fromUtf8("label_IPower_name_106"));
        label_IPower_name_106->setGeometry(QRect(860, 205, 81, 40));
        label_IPower_name_106->setFont(font2);
        label_IPower_name_107 = new QLabel(widget_5);
        label_IPower_name_107->setObjectName(QString::fromUtf8("label_IPower_name_107"));
        label_IPower_name_107->setGeometry(QRect(640, 385, 81, 40));
        label_IPower_name_107->setFont(font2);
        label_IPower_content_67 = new QLabel(widget_5);
        label_IPower_content_67->setObjectName(QString::fromUtf8("label_IPower_content_67"));
        label_IPower_content_67->setGeometry(QRect(730, 390, 121, 30));
        label_IPower_content_67->setFont(font2);
        label_IPower_content_67->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        label_IPower_name_108 = new QLabel(widget_5);
        label_IPower_name_108->setObjectName(QString::fromUtf8("label_IPower_name_108"));
        label_IPower_name_108->setGeometry(QRect(640, 285, 81, 40));
        label_IPower_name_108->setFont(font2);
        label_IPower_content_68 = new QLabel(widget_5);
        label_IPower_content_68->setObjectName(QString::fromUtf8("label_IPower_content_68"));
        label_IPower_content_68->setGeometry(QRect(730, 290, 121, 30));
        label_IPower_content_68->setFont(font2);
        label_IPower_content_68->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        label_IPower_name_109 = new QLabel(widget_5);
        label_IPower_name_109->setObjectName(QString::fromUtf8("label_IPower_name_109"));
        label_IPower_name_109->setGeometry(QRect(860, 385, 81, 40));
        label_IPower_name_109->setFont(font2);
        label_IPower_name_110 = new QLabel(widget_5);
        label_IPower_name_110->setObjectName(QString::fromUtf8("label_IPower_name_110"));
        label_IPower_name_110->setGeometry(QRect(860, 335, 81, 40));
        label_IPower_name_110->setFont(font2);
        label_IPower_name_111 = new QLabel(widget_5);
        label_IPower_name_111->setObjectName(QString::fromUtf8("label_IPower_name_111"));
        label_IPower_name_111->setGeometry(QRect(240, 335, 81, 40));
        label_IPower_name_111->setFont(font2);
        label_IPower_name_112 = new QLabel(widget_5);
        label_IPower_name_112->setObjectName(QString::fromUtf8("label_IPower_name_112"));
        label_IPower_name_112->setGeometry(QRect(20, 285, 81, 40));
        label_IPower_name_112->setFont(font2);
        label_IPower_name_114 = new QLabel(widget_5);
        label_IPower_name_114->setObjectName(QString::fromUtf8("label_IPower_name_114"));
        label_IPower_name_114->setGeometry(QRect(330, 285, 81, 40));
        label_IPower_name_114->setFont(font2);
        label_IPower_content_69 = new QLabel(widget_5);
        label_IPower_content_69->setObjectName(QString::fromUtf8("label_IPower_content_69"));
        label_IPower_content_69->setGeometry(QRect(730, 340, 121, 30));
        label_IPower_content_69->setFont(font2);
        label_IPower_content_69->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        label_IPower_name_113 = new QLabel(widget_5);
        label_IPower_name_113->setObjectName(QString::fromUtf8("label_IPower_name_113"));
        label_IPower_name_113->setGeometry(QRect(20, 335, 81, 40));
        label_IPower_name_113->setFont(font2);
        label_IPower_content_70 = new QLabel(widget_5);
        label_IPower_content_70->setObjectName(QString::fromUtf8("label_IPower_content_70"));
        label_IPower_content_70->setGeometry(QRect(110, 390, 121, 30));
        label_IPower_content_70->setFont(font2);
        label_IPower_content_70->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        label_IPower_name_115 = new QLabel(widget_5);
        label_IPower_name_115->setObjectName(QString::fromUtf8("label_IPower_name_115"));
        label_IPower_name_115->setGeometry(QRect(240, 385, 31, 40));
        label_IPower_name_115->setFont(font2);
        label_IPower_name_116 = new QLabel(widget_5);
        label_IPower_name_116->setObjectName(QString::fromUtf8("label_IPower_name_116"));
        label_IPower_name_116->setGeometry(QRect(20, 385, 81, 40));
        label_IPower_name_116->setFont(font2);
        label_IPower_name_117 = new QLabel(widget_5);
        label_IPower_name_117->setObjectName(QString::fromUtf8("label_IPower_name_117"));
        label_IPower_name_117->setGeometry(QRect(20, 430, 81, 51));
        label_IPower_name_117->setFont(font2);
        label_IPower_content_71 = new QLabel(widget_5);
        label_IPower_content_71->setObjectName(QString::fromUtf8("label_IPower_content_71"));
        label_IPower_content_71->setGeometry(QRect(730, 440, 121, 30));
        label_IPower_content_71->setFont(font2);
        label_IPower_content_71->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        label_IPower_name_118 = new QLabel(widget_5);
        label_IPower_name_118->setObjectName(QString::fromUtf8("label_IPower_name_118"));
        label_IPower_name_118->setGeometry(QRect(860, 435, 81, 40));
        label_IPower_name_118->setFont(font2);
        label_IPower_name_119 = new QLabel(widget_5);
        label_IPower_name_119->setObjectName(QString::fromUtf8("label_IPower_name_119"));
        label_IPower_name_119->setGeometry(QRect(240, 435, 31, 40));
        label_IPower_name_119->setFont(font2);
        label_IPower_content_72 = new QLabel(widget_5);
        label_IPower_content_72->setObjectName(QString::fromUtf8("label_IPower_content_72"));
        label_IPower_content_72->setGeometry(QRect(420, 440, 121, 30));
        label_IPower_content_72->setFont(font2);
        label_IPower_content_72->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        label_IPower_content_73 = new QLabel(widget_5);
        label_IPower_content_73->setObjectName(QString::fromUtf8("label_IPower_content_73"));
        label_IPower_content_73->setGeometry(QRect(110, 440, 121, 30));
        label_IPower_content_73->setFont(font2);
        label_IPower_content_73->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        label_IPower_name_120 = new QLabel(widget_5);
        label_IPower_name_120->setObjectName(QString::fromUtf8("label_IPower_name_120"));
        label_IPower_name_120->setGeometry(QRect(290, 435, 121, 40));
        label_IPower_name_120->setFont(font2);
        label_IPower_name_121 = new QLabel(widget_5);
        label_IPower_name_121->setObjectName(QString::fromUtf8("label_IPower_name_121"));
        label_IPower_name_121->setGeometry(QRect(600, 435, 121, 40));
        label_IPower_name_121->setFont(font2);
        label_IPower_name_122 = new QLabel(widget_5);
        label_IPower_name_122->setObjectName(QString::fromUtf8("label_IPower_name_122"));
        label_IPower_name_122->setGeometry(QRect(550, 435, 41, 40));
        label_IPower_name_122->setFont(font2);
        line_11 = new QFrame(widget_5);
        line_11->setObjectName(QString::fromUtf8("line_11"));
        line_11->setGeometry(QRect(-10, 85, 921, 16));
        line_11->setFrameShape(QFrame::HLine);
        line_11->setFrameShadow(QFrame::Sunken);
        label_IPower_content_74 = new QLabel(widget_5);
        label_IPower_content_74->setObjectName(QString::fromUtf8("label_IPower_content_74"));
        label_IPower_content_74->setGeometry(QRect(420, 35, 121, 30));
        label_IPower_content_74->setFont(font2);
        label_IPower_content_74->setStyleSheet(QString::fromUtf8("background-color: rgb(193, 193, 193);"));
        label_IPower_name_123 = new QLabel(widget_5);
        label_IPower_name_123->setObjectName(QString::fromUtf8("label_IPower_name_123"));
        label_IPower_name_123->setGeometry(QRect(550, 30, 81, 40));
        label_IPower_name_123->setFont(font2);
        label_IPower_content_75 = new QLabel(widget_5);
        label_IPower_content_75->setObjectName(QString::fromUtf8("label_IPower_content_75"));
        label_IPower_content_75->setGeometry(QRect(110, 35, 121, 30));
        label_IPower_content_75->setFont(font2);
        label_IPower_content_75->setStyleSheet(QString::fromUtf8("background-color: rgb(193, 193, 193);"));
        label_IPower_name_124 = new QLabel(widget_5);
        label_IPower_name_124->setObjectName(QString::fromUtf8("label_IPower_name_124"));
        label_IPower_name_124->setGeometry(QRect(240, 30, 81, 40));
        label_IPower_name_124->setFont(font2);
        label_IPower_name_125 = new QLabel(widget_5);
        label_IPower_name_125->setObjectName(QString::fromUtf8("label_IPower_name_125"));
        label_IPower_name_125->setGeometry(QRect(20, 30, 81, 40));
        label_IPower_name_125->setFont(font2);
        label_IPower_name_126 = new QLabel(widget_5);
        label_IPower_name_126->setObjectName(QString::fromUtf8("label_IPower_name_126"));
        label_IPower_name_126->setGeometry(QRect(310, 30, 101, 40));
        label_IPower_name_126->setFont(font2);
        label_IPower_content_98 = new QLabel(widget_5);
        label_IPower_content_98->setObjectName(QString::fromUtf8("label_IPower_content_98"));
        label_IPower_content_98->setGeometry(QRect(730, 35, 121, 30));
        label_IPower_content_98->setFont(font2);
        label_IPower_content_98->setStyleSheet(QString::fromUtf8("background-color: rgb(193, 193, 193);"));
        label_IPower_name_171 = new QLabel(widget_5);
        label_IPower_name_171->setObjectName(QString::fromUtf8("label_IPower_name_171"));
        label_IPower_name_171->setGeometry(QRect(860, 30, 81, 40));
        label_IPower_name_171->setFont(font2);
        label_IPower_name_172 = new QLabel(widget_5);
        label_IPower_name_172->setObjectName(QString::fromUtf8("label_IPower_name_172"));
        label_IPower_name_172->setGeometry(QRect(640, 30, 81, 40));
        label_IPower_name_172->setFont(font2);
        label_IPower_name_173 = new QLabel(widget_5);
        label_IPower_name_173->setObjectName(QString::fromUtf8("label_IPower_name_173"));
        label_IPower_name_173->setGeometry(QRect(550, 210, 81, 40));
        label_IPower_name_173->setFont(font2);
        label_IPower_name_174 = new QLabel(widget_5);
        label_IPower_name_174->setObjectName(QString::fromUtf8("label_IPower_name_174"));
        label_IPower_name_174->setGeometry(QRect(860, 210, 81, 40));
        label_IPower_name_174->setFont(font2);
        pushButton_5 = new QPushButton(centralWidget);
        pushButton_5->setObjectName(QString::fromUtf8("pushButton_5"));
        pushButton_5->setGeometry(QRect(930, 470, 100, 70));
        pushButton_5->setFont(font2);
        pushButton = new QPushButton(centralWidget);
        pushButton->setObjectName(QString::fromUtf8("pushButton"));
        pushButton->setGeometry(QRect(930, 110, 100, 70));
        pushButton->setFont(font2);
        pushButton->setStyleSheet(QString::fromUtf8("border-image: url(:/new/prefix1/btn.qss);"));
        pushButton_2 = new QPushButton(centralWidget);
        pushButton_2->setObjectName(QString::fromUtf8("pushButton_2"));
        pushButton_2->setGeometry(QRect(930, 200, 100, 70));
        pushButton_2->setFont(font2);
        pushButton_3 = new QPushButton(centralWidget);
        pushButton_3->setObjectName(QString::fromUtf8("pushButton_3"));
        pushButton_3->setGeometry(QRect(930, 290, 100, 70));
        pushButton_3->setFont(font2);
        widget_2 = new QWidget(centralWidget);
        widget_2->setObjectName(QString::fromUtf8("widget_2"));
        widget_2->setGeometry(QRect(0, 90, 900, 510));
        QFont font4;
        font4.setPointSize(18);
        widget_2->setFont(font4);
        label_IPower_name = new QLabel(widget_2);
        label_IPower_name->setObjectName(QString::fromUtf8("label_IPower_name"));
        label_IPower_name->setGeometry(QRect(110, 205, 101, 40));
        label_IPower_name->setFont(font3);
        label_Power_name = new QLabel(widget_2);
        label_Power_name->setObjectName(QString::fromUtf8("label_Power_name"));
        label_Power_name->setGeometry(QRect(130, 255, 81, 40));
        label_Power_name->setFont(font3);
        label_power_save_a_content = new QLabel(widget_2);
        label_power_save_a_content->setObjectName(QString::fromUtf8("label_power_save_a_content"));
        label_power_save_a_content->setGeometry(QRect(180, 380, 90, 35));
        label_power_save_a_content->setFont(font3);
        label_power_save_a_content->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        Dial = new QwtDial(widget_2);
        Dial->setObjectName(QString::fromUtf8("Dial"));
        Dial->setGeometry(QRect(190, 20, 201, 151));
        Dial->setProperty("lineWidth", QVariant(4));
        label_power_save_b_content = new QLabel(widget_2);
        label_power_save_b_content->setObjectName(QString::fromUtf8("label_power_save_b_content"));
        label_power_save_b_content->setGeometry(QRect(180, 450, 90, 35));
        label_power_save_b_content->setFont(font3);
        label_power_save_b_content->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        label_IPower_name_4 = new QLabel(widget_2);
        label_IPower_name_4->setObjectName(QString::fromUtf8("label_IPower_name_4"));
        label_IPower_name_4->setGeometry(QRect(10, 360, 161, 71));
        label_IPower_name_4->setFont(font2);
        label_power_saverate_a_content = new QLabel(widget_2);
        label_power_saverate_a_content->setObjectName(QString::fromUtf8("label_power_saverate_a_content"));
        label_power_saverate_a_content->setGeometry(QRect(390, 380, 90, 35));
        label_power_saverate_a_content->setFont(font3);
        label_power_saverate_a_content->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        Dial_2 = new QwtDial(widget_2);
        Dial_2->setObjectName(QString::fromUtf8("Dial_2"));
        Dial_2->setGeometry(QRect(620, 20, 201, 151));
        Dial_2->setProperty("lineWidth", QVariant(4));
        label_power_content = new QLabel(widget_2);
        label_power_content->setObjectName(QString::fromUtf8("label_power_content"));
        label_power_content->setGeometry(QRect(230, 260, 151, 35));
        label_power_content->setFont(font3);
        label_power_content->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        line_2 = new QFrame(widget_2);
        line_2->setObjectName(QString::fromUtf8("line_2"));
        line_2->setGeometry(QRect(0, 350, 1061, 10));
        line_2->setFrameShape(QFrame::HLine);
        line_2->setFrameShadow(QFrame::Sunken);
        label_IPower_name_3 = new QLabel(widget_2);
        label_IPower_name_3->setObjectName(QString::fromUtf8("label_IPower_name_3"));
        label_IPower_name_3->setGeometry(QRect(540, 255, 101, 40));
        label_IPower_name_3->setFont(font3);
        label_IPower_content = new QLabel(widget_2);
        label_IPower_content->setObjectName(QString::fromUtf8("label_IPower_content"));
        label_IPower_content->setGeometry(QRect(230, 210, 151, 35));
        label_IPower_content->setFont(font3);
        label_IPower_content->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        line_3 = new QFrame(widget_2);
        line_3->setObjectName(QString::fromUtf8("line_3"));
        line_3->setGeometry(QRect(0, 420, 521, 20));
        line_3->setFrameShape(QFrame::HLine);
        line_3->setFrameShadow(QFrame::Sunken);
        label_flow_content = new QLabel(widget_2);
        label_flow_content->setObjectName(QString::fromUtf8("label_flow_content"));
        label_flow_content->setGeometry(QRect(660, 260, 151, 35));
        label_flow_content->setFont(font3);
        label_flow_content->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        label_IPower_name_9 = new QLabel(widget_2);
        label_IPower_name_9->setObjectName(QString::fromUtf8("label_IPower_name_9"));
        label_IPower_name_9->setGeometry(QRect(10, 430, 161, 71));
        label_IPower_name_9->setFont(font2);
        label_power_saverate_b_content = new QLabel(widget_2);
        label_power_saverate_b_content->setObjectName(QString::fromUtf8("label_power_saverate_b_content"));
        label_power_saverate_b_content->setGeometry(QRect(390, 450, 90, 35));
        label_power_saverate_b_content->setFont(font3);
        label_power_saverate_b_content->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        label_IPower_name_2 = new QLabel(widget_2);
        label_IPower_name_2->setObjectName(QString::fromUtf8("label_IPower_name_2"));
        label_IPower_name_2->setGeometry(QRect(540, 205, 101, 40));
        label_IPower_name_2->setFont(font3);
        label_IFlow_content = new QLabel(widget_2);
        label_IFlow_content->setObjectName(QString::fromUtf8("label_IFlow_content"));
        label_IFlow_content->setGeometry(QRect(660, 210, 151, 35));
        label_IFlow_content->setFont(font3);
        label_IFlow_content->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        label_IPower_name_10 = new QLabel(widget_2);
        label_IPower_name_10->setObjectName(QString::fromUtf8("label_IPower_name_10"));
        label_IPower_name_10->setGeometry(QRect(310, 375, 81, 40));
        label_IPower_name_10->setFont(font3);
        label_IPower_name_11 = new QLabel(widget_2);
        label_IPower_name_11->setObjectName(QString::fromUtf8("label_IPower_name_11"));
        label_IPower_name_11->setGeometry(QRect(310, 445, 81, 40));
        label_IPower_name_11->setFont(font3);
        line_4 = new QFrame(widget_2);
        line_4->setObjectName(QString::fromUtf8("line_4"));
        line_4->setGeometry(QRect(520, 370, 20, 131));
        line_4->setFrameShape(QFrame::VLine);
        line_4->setFrameShadow(QFrame::Sunken);
        label_IPower_name_13 = new QLabel(widget_2);
        label_IPower_name_13->setObjectName(QString::fromUtf8("label_IPower_name_13"));
        label_IPower_name_13->setGeometry(QRect(550, 375, 101, 40));
        label_IPower_name_13->setFont(font3);
        label_start_time_content = new QLabel(widget_2);
        label_start_time_content->setObjectName(QString::fromUtf8("label_start_time_content"));
        label_start_time_content->setGeometry(QRect(660, 380, 231, 35));
        QFont font5;
        font5.setFamily(QString::fromUtf8("\345\276\256\350\275\257\351\233\205\351\273\221"));
        font5.setPointSize(16);
        label_start_time_content->setFont(font5);
        label_start_time_content->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        label_IPower_name_14 = new QLabel(widget_2);
        label_IPower_name_14->setObjectName(QString::fromUtf8("label_IPower_name_14"));
        label_IPower_name_14->setGeometry(QRect(550, 445, 101, 40));
        label_IPower_name_14->setFont(font3);
        label_end_time_content = new QLabel(widget_2);
        label_end_time_content->setObjectName(QString::fromUtf8("label_end_time_content"));
        label_end_time_content->setGeometry(QRect(660, 450, 231, 35));
        label_end_time_content->setFont(font5);
        label_end_time_content->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        pushButton_6 = new QPushButton(widget_2);
        pushButton_6->setObjectName(QString::fromUtf8("pushButton_6"));
        pushButton_6->setGeometry(QRect(0, 30, 71, 51));
        pushButton_6->setFont(font2);
        pushButton_6->setStyleSheet(QString::fromUtf8("border-image: url(:/new/prefix1/btn.qss);"));
        pushButton_7 = new QPushButton(widget_2);
        pushButton_7->setObjectName(QString::fromUtf8("pushButton_7"));
        pushButton_7->setGeometry(QRect(0, 110, 71, 51));
        pushButton_7->setFont(font2);
        pushButton_7->setStyleSheet(QString::fromUtf8("border-image: url(:/new/prefix1/btn.qss);"));
        label_IPower_name_46 = new QLabel(widget_2);
        label_IPower_name_46->setObjectName(QString::fromUtf8("label_IPower_name_46"));
        label_IPower_name_46->setGeometry(QRect(560, 305, 81, 40));
        label_IPower_name_46->setFont(font3);
        label_loding_rate_content = new QLabel(widget_2);
        label_loding_rate_content->setObjectName(QString::fromUtf8("label_loding_rate_content"));
        label_loding_rate_content->setGeometry(QRect(660, 310, 151, 35));
        label_loding_rate_content->setFont(font3);
        label_loding_rate_content->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        label_Power_name_3 = new QLabel(widget_2);
        label_Power_name_3->setObjectName(QString::fromUtf8("label_Power_name_3"));
        label_Power_name_3->setGeometry(QRect(130, 305, 81, 40));
        label_Power_name_3->setFont(font3);
        label_power_radio_content = new QLabel(widget_2);
        label_power_radio_content->setObjectName(QString::fromUtf8("label_power_radio_content"));
        label_power_radio_content->setGeometry(QRect(230, 310, 151, 35));
        label_power_radio_content->setFont(font3);
        label_power_radio_content->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        label_IPower_name->raise();
        label_Power_name->raise();
        label_power_save_a_content->raise();
        Dial->raise();
        label_power_save_b_content->raise();
        label_IPower_name_4->raise();
        label_power_saverate_a_content->raise();
        Dial_2->raise();
        label_power_content->raise();
        line_2->raise();
        label_IPower_name_3->raise();
        label_IPower_content->raise();
        label_flow_content->raise();
        label_IPower_name_9->raise();
        label_power_saverate_b_content->raise();
        label_IPower_name_2->raise();
        label_IFlow_content->raise();
        label_IPower_name_10->raise();
        label_IPower_name_11->raise();
        line_3->raise();
        line_4->raise();
        label_IPower_name_13->raise();
        label_start_time_content->raise();
        label_IPower_name_14->raise();
        label_end_time_content->raise();
        pushButton_6->raise();
        pushButton_7->raise();
        label_IPower_name_46->raise();
        label_loding_rate_content->raise();
        label_Power_name_3->raise();
        label_power_radio_content->raise();
        widget_6 = new QWidget(centralWidget);
        widget_6->setObjectName(QString::fromUtf8("widget_6"));
        widget_6->setGeometry(QRect(0, 90, 900, 510));
        label_IPower_name_5 = new QLabel(widget_6);
        label_IPower_name_5->setObjectName(QString::fromUtf8("label_IPower_name_5"));
        label_IPower_name_5->setGeometry(QRect(180, 70, 41, 40));
        label_IPower_name_5->setFont(font3);
        label_voltage_a_content = new QLabel(widget_6);
        label_voltage_a_content->setObjectName(QString::fromUtf8("label_voltage_a_content"));
        label_voltage_a_content->setGeometry(QRect(240, 70, 151, 35));
        label_voltage_a_content->setFont(font3);
        label_voltage_a_content->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        label_IPower_name_6 = new QLabel(widget_6);
        label_IPower_name_6->setObjectName(QString::fromUtf8("label_IPower_name_6"));
        label_IPower_name_6->setGeometry(QRect(180, 130, 41, 40));
        label_IPower_name_6->setFont(font3);
        label_voltage_b_content = new QLabel(widget_6);
        label_voltage_b_content->setObjectName(QString::fromUtf8("label_voltage_b_content"));
        label_voltage_b_content->setGeometry(QRect(240, 130, 151, 35));
        label_voltage_b_content->setFont(font3);
        label_voltage_b_content->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        label_IPower_name_7 = new QLabel(widget_6);
        label_IPower_name_7->setObjectName(QString::fromUtf8("label_IPower_name_7"));
        label_IPower_name_7->setGeometry(QRect(180, 190, 41, 40));
        label_IPower_name_7->setFont(font3);
        label_voltage_c_content = new QLabel(widget_6);
        label_voltage_c_content->setObjectName(QString::fromUtf8("label_voltage_c_content"));
        label_voltage_c_content->setGeometry(QRect(240, 190, 151, 35));
        label_voltage_c_content->setFont(font3);
        label_voltage_c_content->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        label_current_c_content = new QLabel(widget_6);
        label_current_c_content->setObjectName(QString::fromUtf8("label_current_c_content"));
        label_current_c_content->setGeometry(QRect(590, 190, 151, 35));
        label_current_c_content->setFont(font3);
        label_current_c_content->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        label_current_b_content = new QLabel(widget_6);
        label_current_b_content->setObjectName(QString::fromUtf8("label_current_b_content"));
        label_current_b_content->setGeometry(QRect(590, 130, 151, 35));
        label_current_b_content->setFont(font3);
        label_current_b_content->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        label_current_a_content = new QLabel(widget_6);
        label_current_a_content->setObjectName(QString::fromUtf8("label_current_a_content"));
        label_current_a_content->setGeometry(QRect(590, 70, 151, 35));
        label_current_a_content->setFont(font3);
        label_current_a_content->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        label_IPower_name_8 = new QLabel(widget_6);
        label_IPower_name_8->setObjectName(QString::fromUtf8("label_IPower_name_8"));
        label_IPower_name_8->setGeometry(QRect(290, 25, 51, 40));
        label_IPower_name_8->setFont(font3);
        label_IPower_name_12 = new QLabel(widget_6);
        label_IPower_name_12->setObjectName(QString::fromUtf8("label_IPower_name_12"));
        label_IPower_name_12->setGeometry(QRect(640, 25, 51, 40));
        label_IPower_name_12->setFont(font3);
        label_IPower_name_15 = new QLabel(widget_6);
        label_IPower_name_15->setObjectName(QString::fromUtf8("label_IPower_name_15"));
        label_IPower_name_15->setGeometry(QRect(400, 70, 41, 40));
        label_IPower_name_15->setFont(font3);
        label_IPower_name_16 = new QLabel(widget_6);
        label_IPower_name_16->setObjectName(QString::fromUtf8("label_IPower_name_16"));
        label_IPower_name_16->setGeometry(QRect(400, 130, 41, 40));
        label_IPower_name_16->setFont(font3);
        label_IPower_name_17 = new QLabel(widget_6);
        label_IPower_name_17->setObjectName(QString::fromUtf8("label_IPower_name_17"));
        label_IPower_name_17->setGeometry(QRect(400, 190, 41, 40));
        label_IPower_name_17->setFont(font3);
        label_IPower_name_18 = new QLabel(widget_6);
        label_IPower_name_18->setObjectName(QString::fromUtf8("label_IPower_name_18"));
        label_IPower_name_18->setGeometry(QRect(750, 70, 41, 40));
        label_IPower_name_18->setFont(font3);
        label_IPower_name_19 = new QLabel(widget_6);
        label_IPower_name_19->setObjectName(QString::fromUtf8("label_IPower_name_19"));
        label_IPower_name_19->setGeometry(QRect(750, 130, 41, 40));
        label_IPower_name_19->setFont(font3);
        label_IPower_name_20 = new QLabel(widget_6);
        label_IPower_name_20->setObjectName(QString::fromUtf8("label_IPower_name_20"));
        label_IPower_name_20->setGeometry(QRect(750, 190, 41, 40));
        label_IPower_name_20->setFont(font3);
        label_IPower_name_21 = new QLabel(widget_6);
        label_IPower_name_21->setObjectName(QString::fromUtf8("label_IPower_name_21"));
        label_IPower_name_21->setGeometry(QRect(170, 305, 51, 40));
        label_IPower_name_21->setFont(font3);
        label_frequency_content = new QLabel(widget_6);
        label_frequency_content->setObjectName(QString::fromUtf8("label_frequency_content"));
        label_frequency_content->setGeometry(QRect(240, 305, 151, 35));
        label_frequency_content->setFont(font3);
        label_frequency_content->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        label_IPower_name_23 = new QLabel(widget_6);
        label_IPower_name_23->setObjectName(QString::fromUtf8("label_IPower_name_23"));
        label_IPower_name_23->setGeometry(QRect(470, 305, 101, 40));
        label_IPower_name_23->setFont(font3);
        label_power_factor_content = new QLabel(widget_6);
        label_power_factor_content->setObjectName(QString::fromUtf8("label_power_factor_content"));
        label_power_factor_content->setGeometry(QRect(590, 305, 151, 35));
        label_power_factor_content->setFont(font3);
        label_power_factor_content->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        label_IPower_name_25 = new QLabel(widget_6);
        label_IPower_name_25->setObjectName(QString::fromUtf8("label_IPower_name_25"));
        label_IPower_name_25->setGeometry(QRect(120, 360, 101, 40));
        label_IPower_name_25->setFont(font3);
        label_active_power_content = new QLabel(widget_6);
        label_active_power_content->setObjectName(QString::fromUtf8("label_active_power_content"));
        label_active_power_content->setGeometry(QRect(240, 360, 151, 35));
        label_active_power_content->setFont(font3);
        label_active_power_content->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        label_IPower_name_26 = new QLabel(widget_6);
        label_IPower_name_26->setObjectName(QString::fromUtf8("label_IPower_name_26"));
        label_IPower_name_26->setGeometry(QRect(400, 360, 41, 40));
        label_IPower_name_26->setFont(font3);
        label_IPower_name_27 = new QLabel(widget_6);
        label_IPower_name_27->setObjectName(QString::fromUtf8("label_IPower_name_27"));
        label_IPower_name_27->setGeometry(QRect(470, 360, 101, 40));
        label_IPower_name_27->setFont(font3);
        label_reactive_power_content = new QLabel(widget_6);
        label_reactive_power_content->setObjectName(QString::fromUtf8("label_reactive_power_content"));
        label_reactive_power_content->setGeometry(QRect(590, 360, 151, 35));
        label_reactive_power_content->setFont(font3);
        label_reactive_power_content->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        label_IPower_name_28 = new QLabel(widget_6);
        label_IPower_name_28->setObjectName(QString::fromUtf8("label_IPower_name_28"));
        label_IPower_name_28->setGeometry(QRect(750, 360, 41, 40));
        label_IPower_name_28->setFont(font3);
        label_IPower_name_29 = new QLabel(widget_6);
        label_IPower_name_29->setObjectName(QString::fromUtf8("label_IPower_name_29"));
        label_IPower_name_29->setGeometry(QRect(400, 415, 51, 40));
        label_IPower_name_29->setFont(font3);
        label_IPower_name_30 = new QLabel(widget_6);
        label_IPower_name_30->setObjectName(QString::fromUtf8("label_IPower_name_30"));
        label_IPower_name_30->setGeometry(QRect(120, 415, 101, 40));
        label_IPower_name_30->setFont(font3);
        label_apparent_power_content = new QLabel(widget_6);
        label_apparent_power_content->setObjectName(QString::fromUtf8("label_apparent_power_content"));
        label_apparent_power_content->setGeometry(QRect(240, 415, 151, 35));
        label_apparent_power_content->setFont(font3);
        label_apparent_power_content->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        line_5 = new QFrame(widget_6);
        line_5->setObjectName(QString::fromUtf8("line_5"));
        line_5->setGeometry(QRect(0, 270, 921, 16));
        line_5->setFrameShape(QFrame::HLine);
        line_5->setFrameShadow(QFrame::Sunken);
        pushButton_8 = new QPushButton(widget_6);
        pushButton_8->setObjectName(QString::fromUtf8("pushButton_8"));
        pushButton_8->setGeometry(QRect(0, 30, 71, 41));
        pushButton_8->setFont(font2);
        pushButton_8->setStyleSheet(QString::fromUtf8("border-image: url(:/new/prefix1/btn.qss);"));
        widget_7 = new QWidget(centralWidget);
        widget_7->setObjectName(QString::fromUtf8("widget_7"));
        widget_7->setGeometry(QRect(0, 90, 900, 510));
        label_IPower_name_31 = new QLabel(widget_7);
        label_IPower_name_31->setObjectName(QString::fromUtf8("label_IPower_name_31"));
        label_IPower_name_31->setGeometry(QRect(760, 60, 41, 40));
        label_IPower_name_31->setFont(font3);
        label_env_temp_content = new QLabel(widget_7);
        label_env_temp_content->setObjectName(QString::fromUtf8("label_env_temp_content"));
        label_env_temp_content->setGeometry(QRect(240, 60, 151, 35));
        label_env_temp_content->setFont(font3);
        label_env_temp_content->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        label_IPower_name_32 = new QLabel(widget_7);
        label_IPower_name_32->setObjectName(QString::fromUtf8("label_IPower_name_32"));
        label_IPower_name_32->setGeometry(QRect(480, 60, 101, 40));
        label_IPower_name_32->setFont(font3);
        label_env_humidity_content = new QLabel(widget_7);
        label_env_humidity_content->setObjectName(QString::fromUtf8("label_env_humidity_content"));
        label_env_humidity_content->setGeometry(QRect(600, 60, 151, 35));
        label_env_humidity_content->setFont(font3);
        label_env_humidity_content->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        label_IPower_name_33 = new QLabel(widget_7);
        label_IPower_name_33->setObjectName(QString::fromUtf8("label_IPower_name_33"));
        label_IPower_name_33->setGeometry(QRect(120, 60, 101, 40));
        label_IPower_name_33->setFont(font3);
        label_IPower_name_34 = new QLabel(widget_7);
        label_IPower_name_34->setObjectName(QString::fromUtf8("label_IPower_name_34"));
        label_IPower_name_34->setGeometry(QRect(400, 60, 41, 40));
        label_IPower_name_34->setFont(font3);
        label_IPower_name_35 = new QLabel(widget_7);
        label_IPower_name_35->setObjectName(QString::fromUtf8("label_IPower_name_35"));
        label_IPower_name_35->setGeometry(QRect(760, 120, 41, 40));
        label_IPower_name_35->setFont(font3);
        label_air_temp_content = new QLabel(widget_7);
        label_air_temp_content->setObjectName(QString::fromUtf8("label_air_temp_content"));
        label_air_temp_content->setGeometry(QRect(240, 120, 151, 35));
        label_air_temp_content->setFont(font3);
        label_air_temp_content->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        label_IPower_name_36 = new QLabel(widget_7);
        label_IPower_name_36->setObjectName(QString::fromUtf8("label_IPower_name_36"));
        label_IPower_name_36->setGeometry(QRect(480, 120, 101, 40));
        label_IPower_name_36->setFont(font3);
        label_air_pressure_content = new QLabel(widget_7);
        label_air_pressure_content->setObjectName(QString::fromUtf8("label_air_pressure_content"));
        label_air_pressure_content->setGeometry(QRect(600, 120, 151, 35));
        label_air_pressure_content->setFont(font3);
        label_air_pressure_content->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        label_IPower_name_37 = new QLabel(widget_7);
        label_IPower_name_37->setObjectName(QString::fromUtf8("label_IPower_name_37"));
        label_IPower_name_37->setGeometry(QRect(120, 120, 101, 40));
        label_IPower_name_37->setFont(font3);
        label_IPower_name_38 = new QLabel(widget_7);
        label_IPower_name_38->setObjectName(QString::fromUtf8("label_IPower_name_38"));
        label_IPower_name_38->setGeometry(QRect(400, 120, 41, 40));
        label_IPower_name_38->setFont(font3);
        label_IPower_name_47 = new QLabel(widget_7);
        label_IPower_name_47->setObjectName(QString::fromUtf8("label_IPower_name_47"));
        label_IPower_name_47->setGeometry(QRect(160, 180, 61, 40));
        label_IPower_name_47->setFont(font3);
        label_IPower_name_48 = new QLabel(widget_7);
        label_IPower_name_48->setObjectName(QString::fromUtf8("label_IPower_name_48"));
        label_IPower_name_48->setGeometry(QRect(400, 175, 41, 40));
        label_IPower_name_48->setFont(font2);
        label_flow_content_1 = new QLabel(widget_7);
        label_flow_content_1->setObjectName(QString::fromUtf8("label_flow_content_1"));
        label_flow_content_1->setGeometry(QRect(240, 180, 151, 35));
        label_flow_content_1->setFont(font3);
        label_flow_content_1->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        pushButton_9 = new QPushButton(widget_7);
        pushButton_9->setObjectName(QString::fromUtf8("pushButton_9"));
        pushButton_9->setGeometry(QRect(0, 30, 71, 41));
        pushButton_9->setFont(font2);
        pushButton_9->setStyleSheet(QString::fromUtf8("border-image: url(:/new/prefix1/btn.qss);"));
        lcdNumber_clock = new QLCDNumber(centralWidget);
        lcdNumber_clock->setObjectName(QString::fromUtf8("lcdNumber_clock"));
        lcdNumber_clock->setGeometry(QRect(850, 20, 201, 31));
        lcdNumber_clock->setFrameShape(QFrame::NoFrame);
        lcdNumber_clock->setDigitCount(8);
        lcdNumber_clock->setSegmentStyle(QLCDNumber::Flat);
        pushButton_10 = new QPushButton(centralWidget);
        pushButton_10->setObjectName(QString::fromUtf8("pushButton_10"));
        pushButton_10->setGeometry(QRect(934, 550, 91, 51));
        MainWindow->setCentralWidget(centralWidget);
        line->raise();
        label->raise();
        label_2->raise();
        pushButton_4->raise();
        pushButton_5->raise();
        pushButton->raise();
        pushButton_2->raise();
        pushButton_3->raise();
        lcdNumber_clock->raise();
        pushButton_10->raise();
        widget_5->raise();
        widget->raise();
        widget_7->raise();
        widget_6->raise();
        widget_2->raise();

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", 0, QApplication::UnicodeUTF8));
        label->setText(QApplication::translate("MainWindow", "\350\212\202\350\203\275\345\210\206\346\236\220\344\273\252", 0, QApplication::UnicodeUTF8));
        label_2->setText(QString());
        pushButton_4->setText(QApplication::translate("MainWindow", "\347\273\223\346\235\237", 0, QApplication::UnicodeUTF8));
        label_IPower_name_180->setText(QApplication::translate("MainWindow", "\345\255\230\345\202\250\346\226\271\345\274\217", 0, QApplication::UnicodeUTF8));
        label_IPower_name_179->setText(QApplication::translate("MainWindow", "\344\272\222\346\204\237\345\231\250\345\217\230\346\257\224", 0, QApplication::UnicodeUTF8));
        label_IPower_name_181->setText(QApplication::translate("MainWindow", "\347\224\265\350\264\271", 0, QApplication::UnicodeUTF8));
        label_IPower_name_182->setText(QApplication::translate("MainWindow", "\351\242\235\345\256\232\345\212\237\347\216\207", 0, QApplication::UnicodeUTF8));
        label_IPower_name_183->setText(QApplication::translate("MainWindow", "\351\242\235\345\256\232\344\272\247\346\260\224\351\207\217", 0, QApplication::UnicodeUTF8));
        label_IPower_name_189->setText(QApplication::translate("MainWindow", "\347\251\272\350\275\275\346\234\200\345\244\247\347\224\265\346\265\201", 0, QApplication::UnicodeUTF8));
        label_IPower_name_190->setText(QApplication::translate("MainWindow", "\345\201\234\346\234\272\347\224\265\346\265\201", 0, QApplication::UnicodeUTF8));
        label_IPower_name_191->setText(QApplication::translate("MainWindow", "\345\212\240\350\275\275\345\216\213\345\212\233", 0, QApplication::UnicodeUTF8));
        label_IPower_name_200->setText(QApplication::translate("MainWindow", "\345\215\270\350\275\275\345\216\213\345\212\233", 0, QApplication::UnicodeUTF8));
        pushButton_12->setText(QApplication::translate("MainWindow", "\344\277\235\345\255\230", 0, QApplication::UnicodeUTF8));
        lineEdit_radio->setText(QString());
        lineEdit_charge->setText(QString());
        lineEdit_power->setText(QString());
        lineEdit_current_idle_max->setText(QString());
        lineEdit_loading_pressure->setText(QString());
        lineEdit_gas->setText(QString());
        lineEdit_current_down_max->setText(QString());
        lineEdit_unloading_pressure->setText(QString());
        label_IPower_content_37->setText(QString());
        label_IPower_name_50->setText(QApplication::translate("MainWindow", "\346\265\213\351\207\217\346\227\266\351\227\264", 0, QApplication::UnicodeUTF8));
        label_IPower_name_52->setText(QApplication::translate("MainWindow", "\345\260\217\346\227\266", 0, QApplication::UnicodeUTF8));
        label_IPower_content_40->setText(QString());
        label_IPower_name_55->setText(QApplication::translate("MainWindow", "\345\260\217\346\227\266", 0, QApplication::UnicodeUTF8));
        label_IPower_name_56->setText(QApplication::translate("MainWindow", "\345\267\245\344\275\234\346\227\266\351\227\264", 0, QApplication::UnicodeUTF8));
        label_IPower_content_45->setText(QString());
        label_IPower_name_65->setText(QApplication::translate("MainWindow", "\345\260\217\346\227\266", 0, QApplication::UnicodeUTF8));
        label_IPower_name_66->setText(QApplication::translate("MainWindow", "\345\276\205\346\234\272\346\227\266\351\227\264", 0, QApplication::UnicodeUTF8));
        label_IPower_content_49->setText(QString());
        label_IPower_name_73->setText(QApplication::translate("MainWindow", "\345\260\217\346\227\266", 0, QApplication::UnicodeUTF8));
        label_IPower_name_74->setText(QApplication::translate("MainWindow", "\347\251\272\350\275\275\346\227\266\351\227\264", 0, QApplication::UnicodeUTF8));
        label_IPower_name_75->setText(QApplication::translate("MainWindow", "\345\260\217\346\227\266", 0, QApplication::UnicodeUTF8));
        label_IPower_content_50->setText(QString());
        label_IPower_content_51->setText(QString());
        label_IPower_name_76->setText(QApplication::translate("MainWindow", "\345\260\217\346\227\266", 0, QApplication::UnicodeUTF8));
        label_IPower_name_77->setText(QApplication::translate("MainWindow", "\345\271\263\345\235\207\346\257\224\345\212\237\347\216\207", 0, QApplication::UnicodeUTF8));
        label_IPower_name_78->setText(QApplication::translate("MainWindow", "\346\273\241\350\275\275\346\227\266\351\227\264", 0, QApplication::UnicodeUTF8));
        label_IPower_content_52->setText(QString());
        label_IPower_name_79->setText(QApplication::translate("MainWindow", "%", 0, QApplication::UnicodeUTF8));
        label_IPower_name_80->setText(QApplication::translate("MainWindow", "\347\251\272\350\275\275\347\216\207", 0, QApplication::UnicodeUTF8));
        label_IPower_name_81->setText(QApplication::translate("MainWindow", "\345\260\217\346\227\266", 0, QApplication::UnicodeUTF8));
        label_IPower_content_53->setText(QString());
        label_IPower_name_84->setText(QApplication::translate("MainWindow", "\346\273\241\350\275\275\347\216\207", 0, QApplication::UnicodeUTF8));
        label_IPower_name_99->setText(QApplication::translate("MainWindow", "\346\273\241\350\275\275\350\200\227\347\224\265", 0, QApplication::UnicodeUTF8));
        label_IPower_content_62->setText(QString());
        label_IPower_content_63->setText(QString());
        label_IPower_name_100->setText(QApplication::translate("MainWindow", "\345\260\217\346\227\266", 0, QApplication::UnicodeUTF8));
        label_IPower_content_64->setText(QString());
        label_IPower_name_101->setText(QApplication::translate("MainWindow", "\345\260\217\346\227\266", 0, QApplication::UnicodeUTF8));
        label_IPower_name_102->setText(QApplication::translate("MainWindow", "%", 0, QApplication::UnicodeUTF8));
        label_IPower_name_103->setText(QApplication::translate("MainWindow", "\346\273\241\350\275\275\347\224\265\350\264\271", 0, QApplication::UnicodeUTF8));
        label_IPower_name_104->setText(QString());
        label_IPower_content_65->setText(QString());
        label_IPower_content_66->setText(QString());
        label_IPower_name_105->setText(QApplication::translate("MainWindow", "\347\251\272\350\275\275\350\200\227\347\224\265", 0, QApplication::UnicodeUTF8));
        label_IPower_name_106->setText(QString());
        label_IPower_name_107->setText(QApplication::translate("MainWindow", "\347\251\272\350\275\275\347\224\265\350\264\271", 0, QApplication::UnicodeUTF8));
        label_IPower_content_67->setText(QString());
        label_IPower_name_108->setText(QApplication::translate("MainWindow", "\345\215\270\350\275\275\346\254\241\346\225\260", 0, QApplication::UnicodeUTF8));
        label_IPower_content_68->setText(QString());
        label_IPower_name_109->setText(QApplication::translate("MainWindow", "\345\260\217\346\227\266", 0, QApplication::UnicodeUTF8));
        label_IPower_name_110->setText(QApplication::translate("MainWindow", "\345\260\217\346\227\266", 0, QApplication::UnicodeUTF8));
        label_IPower_name_111->setText(QApplication::translate("MainWindow", "\345\260\217\346\227\266", 0, QApplication::UnicodeUTF8));
        label_IPower_name_112->setText(QApplication::translate("MainWindow", "\346\200\273\344\272\247\346\260\224\351\207\217", 0, QApplication::UnicodeUTF8));
        label_IPower_name_114->setText(QApplication::translate("MainWindow", "\345\212\240\350\275\275\346\254\241\346\225\260", 0, QApplication::UnicodeUTF8));
        label_IPower_content_69->setText(QString());
        label_IPower_name_113->setText(QApplication::translate("MainWindow", "\346\200\273\350\200\227\347\224\265\351\207\217", 0, QApplication::UnicodeUTF8));
        label_IPower_content_70->setText(QString());
        label_IPower_name_115->setText(QApplication::translate("MainWindow", "\345\205\203", 0, QApplication::UnicodeUTF8));
        label_IPower_name_116->setText(QApplication::translate("MainWindow", "\347\224\265\350\264\271\346\200\273\351\242\235", 0, QApplication::UnicodeUTF8));
        label_IPower_name_117->setText(QApplication::translate("MainWindow", "\346\257\217\347\253\213\346\226\271\347\261\263\n"
"\346\260\224\344\275\223\346\210\220\346\234\254", 0, QApplication::UnicodeUTF8));
        label_IPower_content_71->setText(QString());
        label_IPower_name_118->setText(QApplication::translate("MainWindow", "\345\260\217\346\227\266", 0, QApplication::UnicodeUTF8));
        label_IPower_name_119->setText(QApplication::translate("MainWindow", "\345\205\203", 0, QApplication::UnicodeUTF8));
        label_IPower_content_72->setText(QString());
        label_IPower_content_73->setText(QString());
        label_IPower_name_120->setText(QApplication::translate("MainWindow", "\346\273\241\350\275\275\350\200\227\347\224\265\345\215\240\346\257\224", 0, QApplication::UnicodeUTF8));
        label_IPower_name_121->setText(QApplication::translate("MainWindow", "\347\251\272\350\275\275\350\200\227\347\224\265\345\215\240\346\257\224", 0, QApplication::UnicodeUTF8));
        label_IPower_name_122->setText(QApplication::translate("MainWindow", "%", 0, QApplication::UnicodeUTF8));
        label_IPower_content_74->setText(QString());
        label_IPower_name_123->setText(QApplication::translate("MainWindow", "\345\260\217\346\227\266", 0, QApplication::UnicodeUTF8));
        label_IPower_content_75->setText(QString());
        label_IPower_name_124->setText(QApplication::translate("MainWindow", "\345\260\217\346\227\266", 0, QApplication::UnicodeUTF8));
        label_IPower_name_125->setText(QApplication::translate("MainWindow", "\351\242\235\345\256\232\345\212\237\347\216\207", 0, QApplication::UnicodeUTF8));
        label_IPower_name_126->setText(QApplication::translate("MainWindow", "\351\242\235\345\256\232\344\272\247\346\260\224\351\207\217", 0, QApplication::UnicodeUTF8));
        label_IPower_content_98->setText(QString());
        label_IPower_name_171->setText(QApplication::translate("MainWindow", "\347\224\265\350\264\271", 0, QApplication::UnicodeUTF8));
        label_IPower_name_172->setText(QApplication::translate("MainWindow", "\347\224\265\350\264\271", 0, QApplication::UnicodeUTF8));
        label_IPower_name_173->setText(QApplication::translate("MainWindow", "%", 0, QApplication::UnicodeUTF8));
        label_IPower_name_174->setText(QApplication::translate("MainWindow", "%", 0, QApplication::UnicodeUTF8));
        pushButton_5->setText(QApplication::translate("MainWindow", "\345\210\206\346\236\220", 0, QApplication::UnicodeUTF8));
        pushButton->setText(QApplication::translate("MainWindow", "\350\256\276\347\275\256", 0, QApplication::UnicodeUTF8));
        pushButton_2->setText(QApplication::translate("MainWindow", "\346\237\245\347\234\213", 0, QApplication::UnicodeUTF8));
        pushButton_3->setText(QApplication::translate("MainWindow", "\345\274\200\345\247\213", 0, QApplication::UnicodeUTF8));
        label_IPower_name->setText(QApplication::translate("MainWindow", "\347\236\254\346\227\266\345\212\237\347\216\207", 0, QApplication::UnicodeUTF8));
        label_Power_name->setText(QApplication::translate("MainWindow", "\347\224\250\347\224\265\351\207\217", 0, QApplication::UnicodeUTF8));
        label_power_save_a_content->setText(QString());
        label_power_save_b_content->setText(QString());
        label_IPower_name_4->setText(QApplication::translate("MainWindow", "\351\207\207\347\224\250\344\270\200\347\272\247\350\203\275\346\225\210\346\234\272\347\273\204\n"
"\351\242\204\350\256\241\346\257\217\345\260\217\346\227\266\350\212\202\347\224\265\351\207\217", 0, QApplication::UnicodeUTF8));
        label_power_saverate_a_content->setText(QString());
        label_power_content->setText(QString());
        label_IPower_name_3->setText(QApplication::translate("MainWindow", "\347\264\257\350\256\241\346\265\201\351\207\217", 0, QApplication::UnicodeUTF8));
        label_IPower_content->setText(QString());
        label_flow_content->setText(QString());
        label_IPower_name_9->setText(QApplication::translate("MainWindow", "\351\207\207\347\224\250\346\260\270\347\243\201\345\217\230\351\242\221\346\234\272\347\273\204\n"
"\351\242\204\350\256\241\346\257\217\345\260\217\346\227\266\350\212\202\347\224\265\351\207\217", 0, QApplication::UnicodeUTF8));
        label_power_saverate_b_content->setText(QString());
        label_IPower_name_2->setText(QApplication::translate("MainWindow", "\347\236\254\346\227\266\346\265\201\351\207\217", 0, QApplication::UnicodeUTF8));
        label_IFlow_content->setText(QString());
        label_IPower_name_10->setText(QApplication::translate("MainWindow", "\350\212\202\350\203\275\347\216\207", 0, QApplication::UnicodeUTF8));
        label_IPower_name_11->setText(QApplication::translate("MainWindow", "\350\212\202\350\203\275\347\216\207", 0, QApplication::UnicodeUTF8));
        label_IPower_name_13->setText(QApplication::translate("MainWindow", "\345\274\200\345\247\213\346\227\266\351\227\264", 0, QApplication::UnicodeUTF8));
        label_start_time_content->setText(QString());
        label_IPower_name_14->setText(QApplication::translate("MainWindow", "\346\214\201\347\273\255\346\227\266\351\227\264", 0, QApplication::UnicodeUTF8));
        label_end_time_content->setText(QString());
        pushButton_6->setText(QApplication::translate("MainWindow", "\347\224\265\350\241\250", 0, QApplication::UnicodeUTF8));
        pushButton_7->setText(QApplication::translate("MainWindow", "\344\274\240\346\204\237\345\231\250", 0, QApplication::UnicodeUTF8));
        label_IPower_name_46->setText(QApplication::translate("MainWindow", "\345\212\240\350\275\275\347\216\207", 0, QApplication::UnicodeUTF8));
        label_loding_rate_content->setText(QString());
        label_Power_name_3->setText(QApplication::translate("MainWindow", "\346\257\224\345\212\237\347\216\207", 0, QApplication::UnicodeUTF8));
        label_power_radio_content->setText(QString());
        label_IPower_name_5->setText(QApplication::translate("MainWindow", "A\347\233\270", 0, QApplication::UnicodeUTF8));
        label_voltage_a_content->setText(QString());
        label_IPower_name_6->setText(QApplication::translate("MainWindow", "B\347\233\270", 0, QApplication::UnicodeUTF8));
        label_voltage_b_content->setText(QString());
        label_IPower_name_7->setText(QApplication::translate("MainWindow", "C\347\233\270", 0, QApplication::UnicodeUTF8));
        label_voltage_c_content->setText(QString());
        label_current_c_content->setText(QString());
        label_current_b_content->setText(QString());
        label_current_a_content->setText(QString());
        label_IPower_name_8->setText(QApplication::translate("MainWindow", "\347\224\265\345\216\213", 0, QApplication::UnicodeUTF8));
        label_IPower_name_12->setText(QApplication::translate("MainWindow", "\347\224\265\346\265\201", 0, QApplication::UnicodeUTF8));
        label_IPower_name_15->setText(QApplication::translate("MainWindow", "V", 0, QApplication::UnicodeUTF8));
        label_IPower_name_16->setText(QApplication::translate("MainWindow", "V", 0, QApplication::UnicodeUTF8));
        label_IPower_name_17->setText(QApplication::translate("MainWindow", "V", 0, QApplication::UnicodeUTF8));
        label_IPower_name_18->setText(QApplication::translate("MainWindow", "A", 0, QApplication::UnicodeUTF8));
        label_IPower_name_19->setText(QApplication::translate("MainWindow", "A", 0, QApplication::UnicodeUTF8));
        label_IPower_name_20->setText(QApplication::translate("MainWindow", "A", 0, QApplication::UnicodeUTF8));
        label_IPower_name_21->setText(QApplication::translate("MainWindow", "\351\242\221\347\216\207", 0, QApplication::UnicodeUTF8));
        label_frequency_content->setText(QString());
        label_IPower_name_23->setText(QApplication::translate("MainWindow", "\345\212\237\347\216\207\345\233\240\347\264\240", 0, QApplication::UnicodeUTF8));
        label_power_factor_content->setText(QString());
        label_IPower_name_25->setText(QApplication::translate("MainWindow", "\346\234\211\345\212\237\345\212\237\347\216\207", 0, QApplication::UnicodeUTF8));
        label_active_power_content->setText(QString());
        label_IPower_name_26->setText(QApplication::translate("MainWindow", "Kw", 0, QApplication::UnicodeUTF8));
        label_IPower_name_27->setText(QApplication::translate("MainWindow", "\346\227\240\345\212\237\345\212\237\347\216\207", 0, QApplication::UnicodeUTF8));
        label_reactive_power_content->setText(QString());
        label_IPower_name_28->setText(QApplication::translate("MainWindow", "Kavr", 0, QApplication::UnicodeUTF8));
        label_IPower_name_29->setText(QApplication::translate("MainWindow", "KVA", 0, QApplication::UnicodeUTF8));
        label_IPower_name_30->setText(QApplication::translate("MainWindow", "\350\247\206\345\234\250\345\212\237\347\216\207", 0, QApplication::UnicodeUTF8));
        label_apparent_power_content->setText(QString());
        pushButton_8->setText(QApplication::translate("MainWindow", "\350\277\224\345\233\236", 0, QApplication::UnicodeUTF8));
        label_IPower_name_31->setText(QApplication::translate("MainWindow", "Kavr", 0, QApplication::UnicodeUTF8));
        label_env_temp_content->setText(QString());
        label_IPower_name_32->setText(QApplication::translate("MainWindow", "\347\216\257\345\242\203\346\271\277\345\272\246", 0, QApplication::UnicodeUTF8));
        label_env_humidity_content->setText(QString());
        label_IPower_name_33->setText(QApplication::translate("MainWindow", "\347\216\257\345\242\203\346\270\251\345\272\246", 0, QApplication::UnicodeUTF8));
        label_IPower_name_34->setText(QApplication::translate("MainWindow", "Kw", 0, QApplication::UnicodeUTF8));
        label_IPower_name_35->setText(QApplication::translate("MainWindow", "Kavr", 0, QApplication::UnicodeUTF8));
        label_air_temp_content->setText(QString());
        label_IPower_name_36->setText(QApplication::translate("MainWindow", "\346\216\222\346\260\224\345\216\213\345\212\233", 0, QApplication::UnicodeUTF8));
        label_air_pressure_content->setText(QString());
        label_IPower_name_37->setText(QApplication::translate("MainWindow", "\346\216\222\346\260\224\346\270\251\345\272\246", 0, QApplication::UnicodeUTF8));
        label_IPower_name_38->setText(QApplication::translate("MainWindow", "Kw", 0, QApplication::UnicodeUTF8));
        label_IPower_name_47->setText(QApplication::translate("MainWindow", "\346\265\201\351\207\217", 0, QApplication::UnicodeUTF8));
        label_IPower_name_48->setText(QString());
        label_flow_content_1->setText(QString());
        pushButton_9->setText(QApplication::translate("MainWindow", "\350\277\224\345\233\236", 0, QApplication::UnicodeUTF8));
        pushButton_10->setText(QApplication::translate("MainWindow", "PushButton", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
